;; Awsum WASM codegen — WAT text format for inspection.
;; Binary .wasm is generated by assembleWASM for execution.
(module
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $args_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_get" (func $args_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 126))
  (global $__wl_buf (mut i32) (i32.const 0))
  (global $__wl_top (mut i32) (i32.const 0))
  (global $__wl_cap (mut i32) (i32.const 0))
  (data (i32.const 64) "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00")
  (data (i32.const 84) "\00\00\00\00\00\00\00\00\00\00\00\00\01\00\00\00\01\00\00\00A")
  (data (i32.const 105) "\00\00\00\00\00\00\00\00\00\00\00\00\01\00\00\00\01\00\00\00B")
  (table 1 funcref)
  (elem (i32.const 0) $v_runIO)
  (func $__alloc (param i32) (result i32)
    local.get 0
    i32.const 0
    call 10)

  (func $__free (param i32)
    (local i32)
    (local i32)
    (local i32)
    local.get 0
    i32.const 12
    i32.sub
    i32.load
    local.set 1
    local.get 1
    i32.eqz
    if
      return
    end
    local.get 1
    i32.const 4096
    i32.gt_u
    if
      return
    end
    i32.const 24
    local.get 1
    i32.ctz
    i32.const 3
    i32.sub
    i32.const 2
    i32.shl
    i32.add
    local.set 2
    local.get 2
    i32.load
    local.set 3
    local.get 0
    i32.const 4
    i32.sub
    local.get 3
    i32.store
    local.get 2
    local.get 0
    i32.const 12
    i32.sub
    i32.store)

  (func $__memcpy (param i32 i32 i32)
    (local i32)
    i32.const 0
    local.set 3
    block
      loop
        local.get 3
        local.get 2
        i32.ge_u
        br_if 1
        local.get 0
        local.get 3
        i32.add
        local.get 1
        local.get 3
        i32.add
        i32.load8_u
        i32.store8
        local.get 3
        i32.const 1
        i32.add
        local.set 3
        br 0
      end
    end)

  (func $__print (param i32) (result i32)
    (local i32)
    (local i32)
    local.get 0
    i32.load
    local.set 1
    i32.const 0
    local.get 0
    i32.const 8
    i32.add
    i32.store
    i32.const 0
    local.get 1
    i32.store offset=4
    i32.const 1
    i32.const 0
    i32.const 1
    i32.const 8
    call 0
    drop
    i32.const 4
    call 4
    local.set 2
    local.get 2
    i32.const 0
    i32.store
    local.get 0
    call 12
    local.get 2)

  (func $__box_i32 (param i32) (result i32)
    (local i32)
    i32.const 4
    call 4
    local.set 1
    local.get 1
    local.get 0
    i32.store
    local.get 1)

  (func $__show_i32 (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    local.get 0
    i32.load
    local.set 1
    i32.const 24
    call 4
    local.set 2
    i32.const 23
    local.set 3
    local.get 1
    i32.const 0
    i32.lt_s
    if
      i32.const 1
      local.set 4
      i32.const 0
      local.get 1
      i32.sub
      local.set 5
    else
      i32.const 0
      local.set 4
      local.get 1
      local.set 5
    end
    local.get 5
    i32.eqz
    if
      local.get 2
      local.get 3
      i32.add
      i32.const 48
      i32.store8
      local.get 3
      i32.const 1
      i32.sub
      local.set 3
    else
      block
        loop
          local.get 5
          i32.eqz
          br_if 1
          local.get 5
          i32.const 10
          i32.rem_u
          local.set 6
          local.get 2
          local.get 3
          i32.add
          local.get 6
          i32.const 48
          i32.add
          i32.store8
          local.get 3
          i32.const 1
          i32.sub
          local.set 3
          local.get 5
          i32.const 10
          i32.div_u
          local.set 5
          br 0
        end
      end
    end
    local.get 4
    if
      local.get 2
      local.get 3
      i32.add
      i32.const 45
      i32.store8
      local.get 3
      i32.const 1
      i32.sub
      local.set 3
    end
    i32.const 23
    local.get 3
    i32.sub
    local.set 7
    local.get 2
    i32.const 8
    i32.add
    local.get 2
    local.get 3
    i32.add
    i32.const 1
    i32.add
    local.get 7
    call 6
    local.get 2
    local.get 7
    i32.store
    local.get 2
    local.get 7
    i32.store offset=4
    local.get 0
    call 12
    local.get 2)

  (func $__alloc_shaped (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    i32.const 1
    i32.const 32
    local.get 0
    i32.const 1
    i32.sub
    i32.clz
    i32.sub
    i32.shl
    local.set 2
    local.get 2
    i32.const 8
    i32.lt_u
    if
      i32.const 8
      local.set 2
    end
    local.get 2
    i32.const 4096
    i32.le_u
    if
      i32.const 24
      local.get 2
      i32.ctz
      i32.const 3
      i32.sub
      i32.const 2
      i32.shl
      i32.add
      local.set 3
      local.get 3
      i32.load
      local.set 4
      local.get 4
      if
        local.get 3
        local.get 4
        i32.const 8
        i32.add
        i32.load
        i32.store
        local.get 4
        i32.const 4
        i32.add
        i32.const 1
        i32.store
        local.get 4
        i32.const 8
        i32.add
        local.get 1
        i32.store
        local.get 4
        i32.const 12
        i32.add
        return
      end
    end
    global.get 0
    i32.const 3
    i32.add
    i32.const -4
    i32.and
    local.set 5
    local.get 5
    i32.const 12
    i32.add
    local.get 2
    i32.add
    global.set 0
    loop
      global.get 0
      memory.size
      i32.const 65536
      i32.mul
      i32.gt_u
      if
        i32.const 1
        memory.grow
        i32.const -1
        i32.eq
        if
          unreachable
        end
        br 1
      end
    end
    local.get 5
    local.get 2
    i32.store
    local.get 5
    i32.const 4
    i32.add
    i32.const 1
    i32.store
    local.get 5
    i32.const 8
    i32.add
    local.get 1
    i32.store
    local.get 5
    i32.const 12
    i32.add)

  (func $__inc_ref (param i32)
    (local i32)
    local.get 0
    i32.const 12
    i32.sub
    i32.load
    local.set 1
    local.get 1
    i32.eqz
    if
      return
    end
    local.get 0
    i32.const 8
    i32.sub
    local.get 0
    i32.const 8
    i32.sub
    i32.load
    i32.const 1
    i32.add
    i32.store)

  (func $__free_recursive (param i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    block
      loop
        local.get 0
        i32.const 12
        i32.sub
        i32.load
        local.set 1
        block
          local.get 1
          i32.eqz
          br_if 0
          local.get 0
          i32.const 8
          i32.sub
          i32.load
          i32.const 1
          i32.sub
          local.set 2
          local.get 0
          i32.const 8
          i32.sub
          local.get 2
          i32.store
          local.get 2
          br_if 0
          local.get 0
          i32.const 4
          i32.sub
          i32.load
          local.set 3
          local.get 3
          i32.eqz
          if
            local.get 0
            call 5
            br 1
          end
          i32.const 1
          local.set 4
          block
            loop
              local.get 4
              local.get 3
              i32.ge_u
              br_if 1
              local.get 0
              local.get 4
              i32.const 2
              i32.shl
              i32.add
              i32.load
              call 13
              local.get 4
              i32.const 1
              i32.add
              local.set 4
              br 0
            end
          end
          local.get 0
          local.get 3
          i32.const 2
          i32.shl
          i32.add
          i32.load
          local.set 4
          local.get 0
          call 5
          local.get 4
          local.set 0
          br 1
        end
        global.get 2
        local.set 5
        local.get 5
        i32.eqz
        br_if 1
        local.get 5
        i32.const 1
        i32.sub
        local.set 5
        local.get 5
        global.set 2
        global.get 1
        local.get 5
        i32.const 2
        i32.shl
        i32.add
        i32.load
        local.set 0
        br 0
      end
    end)

  (func $__free_worklist_push (param i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    global.get 2
    local.set 1
    global.get 3
    local.set 2
    local.get 1
    local.get 2
    i32.eq
    if
      local.get 2
      i32.eqz
      if (result i32)
        i32.const 16
      else
        local.get 2
        i32.const 1
        i32.shl
      end
      local.set 3
      local.get 3
      i32.const 2
      i32.shl
      i32.const 0
      call 10
      local.set 4
      global.get 1
      local.set 5
      i32.const 0
      local.set 6
      block
        loop
          local.get 6
          local.get 1
          i32.ge_u
          br_if 1
          local.get 4
          local.get 6
          i32.const 2
          i32.shl
          i32.add
          local.get 5
          local.get 6
          i32.const 2
          i32.shl
          i32.add
          i32.load
          i32.store
          local.get 6
          i32.const 1
          i32.add
          local.set 6
          br 0
        end
      end
      local.get 5
      if
        local.get 5
        call 5
      end
      local.get 4
      global.set 1
      local.get 3
      global.set 3
    end
    global.get 1
    local.get 1
    i32.const 2
    i32.shl
    i32.add
    local.get 0
    i32.store
    local.get 1
    i32.const 1
    i32.add
    global.set 2)

  (func $v_runIO (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 5
      i32.eq
      if (result i32)
        block (result i32)
          local.get 0
          i32.load offset=4
          local.tee 2
          call 11
          local.get 2
          local.set 2
          local.get 0
          call 12
          local.get 2
        end
      else
        local.get 0
        i32.load offset=4
        local.tee 3
        call 11
        local.get 3
        call 7
        local.set 3
        local.get 0
        i32.load offset=8
        local.tee 5
        call 11
        local.get 5
        local.set 4
        local.get 0
        call 12
        local.get 3
        call 12
        local.get 4
        local.set 0
        br 1
      end
    end)

  (func $v_oa (result i32)
    (local i32)
    i32.const 8
    i32.const 1
    call 10
    local.set 0
    local.get 0
    i32.const 4
    i32.store
    local.get 0
    i32.const 2
    call 8
    i32.store offset=4
    local.get 0)

  (func $v_main (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    i32.const 12
    i32.const 2
    call 10
    local.set 0
    local.get 0
    i32.const 7
    i32.store
    local.get 0
    call 15
    local.set 1
    block (result i32)
      local.get 1
      i32.load
      i32.const 3
      i32.eq
      if (result i32)
        i32.const 8
        i32.const 1
        call 10
        local.set 3
        local.get 3
        i32.const 3
        i32.store
        local.get 3
        i32.const 8
        i32.const 1
        call 10
        local.set 4
        local.get 4
        i32.const 332136403
        i32.store
        local.get 4
        local.get 1
        i32.load offset=4
        local.tee 5
        call 11
        local.get 5
        i32.store offset=4
        local.get 4
        i32.store offset=4
        local.get 3
      else
        local.get 1
        local.tee 3
        call 11
        local.get 3
      end
      local.set 2
      local.get 1
      call 12
      local.get 2
    end
    local.set 1
    block (result i32)
      local.get 1
      i32.load
      i32.const 3
      i32.eq
      if (result i32)
        local.get 1
        local.tee 3
        call 11
        local.get 3
      else
        i32.const 8
        i32.const 1
        call 10
        local.set 3
        local.get 3
        i32.const 3
        i32.store
        local.get 3
        i32.const 4
        i32.const 0
        call 10
        local.set 4
        local.get 4
        i32.const 25
        i32.store
        local.get 4
        i32.store offset=4
        local.get 3
        local.set 3
        block (result i32)
          local.get 3
          i32.load
          i32.const 3
          i32.eq
          if (result i32)
            i32.const 8
            i32.const 1
            call 10
            local.set 5
            local.get 5
            i32.const 3
            i32.store
            local.get 5
            i32.const 8
            i32.const 1
            call 10
            local.set 6
            local.get 6
            i32.const 348914022
            i32.store
            local.get 6
            local.get 3
            i32.load offset=4
            local.tee 7
            call 11
            local.get 7
            i32.store offset=4
            local.get 6
            i32.store offset=4
            local.get 5
          else
            local.get 3
            local.tee 5
            call 11
            local.get 5
          end
          local.set 4
          local.get 3
          call 12
          local.get 4
        end
      end
      local.set 2
      local.get 1
      call 12
      local.get 2
    end
    local.set 1
    block (result i32)
      local.get 1
      i32.load
      i32.const 3
      i32.eq
      if (result i32)
        local.get 1
        i32.load offset=4
        local.tee 3
        call 11
        local.get 3
        local.set 3
        local.get 3
        i32.load
        i32.const 332136403
        i32.eq
        if (result i32)
          local.get 3
          call 12
          i32.const 96
        else
          local.get 3
          call 12
          i32.const 117
        end
      else
        local.get 1
        i32.load offset=4
        local.tee 3
        call 11
        local.get 3
        call 9
      end
      local.set 2
      local.get 1
      call 12
      local.get 2
    end
    i32.store offset=4
    local.get 0
    i32.const 8
    i32.const 1
    call 10
    local.set 1
    local.get 1
    i32.const 5
    i32.store
    local.get 1
    i32.const 4
    i32.const 0
    call 10
    local.set 2
    local.get 2
    i32.const 0
    i32.store
    local.get 2
    i32.store offset=4
    local.get 1
    i32.store offset=8
    local.get 0)

  (func $_start
    call 16
    call 14
    drop)
)