; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_pureEither(Ljava/lang/Object;)Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  areturn
.end method


.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    2: L_tco_arm_2
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_1
  dup
  iconst_2
  aaload
  astore_2
  pop
  aload_1
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_2
  astore_0
  goto L_tco_loop
.end method


.method static v_opA()Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method


.method static v_opB()Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method


.method static v_main(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_opA()Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  sipush 2252990199
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  invokestatic AwsumMain/v_opB()Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  sipush 2269767818
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  invokestatic AwsumMain/v_pureEither(Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  goto L_join
L_join:
  invokestatic AwsumMain/v__let_2(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__let_2(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    2252990199: L_arm_2252990199
    2269767818: L_arm_2269767818
    2448244154: L_arm_2448244154
    default: L_arm_2252990199
L_arm_2252990199:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "ERR_A"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_arm_2269767818:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "ERR_B"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_arm_2448244154:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "PARSE_ERROR"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_join:
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/toString()Ljava/lang/String;
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_join:
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  arraylength
  iconst_1
  if_icmpge has_arg
  ldc ""
  goto call_main
has_arg:
  aload_0
  iconst_0
  aaload
call_main:
  astore_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  invokestatic AwsumMain/v_main(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
