;; Awsum WASM codegen — WAT text format for inspection.
;; Binary .wasm is generated by assembleWASM for execution.
(module
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $args_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_get" (func $args_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 147))
  (global $__wl_buf (mut i32) (i32.const 0))
  (global $__wl_top (mut i32) (i32.const 0))
  (global $__wl_cap (mut i32) (i32.const 0))
  (data (i32.const 64) "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00")
  (data (i32.const 84) "\00\00\00\00\00\00\00\00\00\00\00\00\08\00\00\00\08\00\00\00UNPAIRED")
  (data (i32.const 112) "\00\00\00\00\00\00\00\00\00\00\00\00\0f\00\00\00\0f\00\00\00STRING_TOO_LONG")
  (table 11 funcref)
  (elem (i32.const 0) $v_runIO $v__cps_mklist $v__apply_mklist $v__cps_mkmb $v__apply_mkmb $v__cps__df_handleErrorIO_0 $v__apply__df_handleErrorIO_0 $v__cps__df__rowmono_0_andThenIO_4 $v__apply__df__rowmono_0_andThenIO_4 $v__cps__scc__apply1__df__lam_14_5__df__lam_9_1 $v__apply__scc__apply1__df__lam_14_5__df__lam_9_1)
  (func $__alloc (param i32) (result i32)
    local.get 0
    i32.const 0
    call 15)

  (func $__free (param i32)
    (local i32)
    (local i32)
    (local i32)
    local.get 0
    i32.const 12
    i32.sub
    i32.load
    local.set 1
    local.get 1
    i32.eqz
    if
      return
    end
    local.get 1
    i32.const 4096
    i32.gt_u
    if
      return
    end
    i32.const 24
    local.get 1
    i32.ctz
    i32.const 3
    i32.sub
    i32.const 2
    i32.shl
    i32.add
    local.set 2
    local.get 2
    i32.load
    local.set 3
    local.get 0
    i32.const 4
    i32.sub
    local.get 3
    i32.store
    local.get 2
    local.get 0
    i32.const 12
    i32.sub
    i32.store)

  (func $__memcpy (param i32 i32 i32)
    (local i32)
    i32.const 0
    local.set 3
    block
      loop
        local.get 3
        local.get 2
        i32.ge_u
        br_if 1
        local.get 0
        local.get 3
        i32.add
        local.get 1
        local.get 3
        i32.add
        i32.load8_u
        i32.store8
        local.get 3
        i32.const 1
        i32.add
        local.set 3
        br 0
      end
    end)

  (func $__print (param i32) (result i32)
    (local i32)
    (local i32)
    local.get 0
    i32.load
    local.set 1
    i32.const 0
    local.get 0
    i32.const 8
    i32.add
    i32.store
    i32.const 0
    local.get 1
    i32.store offset=4
    i32.const 1
    i32.const 0
    i32.const 1
    i32.const 8
    call 0
    drop
    i32.const 4
    call 4
    local.set 2
    local.get 2
    i32.const 0
    i32.store
    local.get 0
    call 17
    local.get 2)

  (func $__box_i32 (param i32) (result i32)
    (local i32)
    i32.const 4
    call 4
    local.set 1
    local.get 1
    local.get 0
    i32.store
    local.get 1)

  (func $__show_i32 (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    local.get 0
    i32.load
    local.set 1
    i32.const 24
    call 4
    local.set 2
    i32.const 23
    local.set 3
    local.get 1
    i32.const 0
    i32.lt_s
    if
      i32.const 1
      local.set 4
      i32.const 0
      local.get 1
      i32.sub
      local.set 5
    else
      i32.const 0
      local.set 4
      local.get 1
      local.set 5
    end
    local.get 5
    i32.eqz
    if
      local.get 2
      local.get 3
      i32.add
      i32.const 48
      i32.store8
      local.get 3
      i32.const 1
      i32.sub
      local.set 3
    else
      block
        loop
          local.get 5
          i32.eqz
          br_if 1
          local.get 5
          i32.const 10
          i32.rem_u
          local.set 6
          local.get 2
          local.get 3
          i32.add
          local.get 6
          i32.const 48
          i32.add
          i32.store8
          local.get 3
          i32.const 1
          i32.sub
          local.set 3
          local.get 5
          i32.const 10
          i32.div_u
          local.set 5
          br 0
        end
      end
    end
    local.get 4
    if
      local.get 2
      local.get 3
      i32.add
      i32.const 45
      i32.store8
      local.get 3
      i32.const 1
      i32.sub
      local.set 3
    end
    i32.const 23
    local.get 3
    i32.sub
    local.set 7
    local.get 2
    i32.const 8
    i32.add
    local.get 2
    local.get 3
    i32.add
    i32.const 1
    i32.add
    local.get 7
    call 6
    local.get 2
    local.get 7
    i32.store
    local.get 2
    local.get 7
    i32.store offset=4
    local.get 0
    call 17
    local.get 2)

  (func $__predInt32 (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    local.get 0
    i32.load
    local.set 1
    local.get 1
    i32.const -2147483648
    i32.eq
    if
      i32.const 4
      call 4
      local.set 2
      local.get 2
      i32.const 17
      i32.store
      i32.const 8
      i32.const 1
      call 15
      local.set 4
      local.get 4
      i32.const 3
      i32.store
      local.get 4
      local.get 2
      i32.store offset=4
    else
      i32.const 4
      call 4
      local.set 3
      local.get 3
      local.get 1
      i32.const 1
      i32.sub
      i32.store
      i32.const 8
      i32.const 1
      call 15
      local.set 4
      local.get 4
      i32.const 4
      i32.store
      local.get 4
      local.get 3
      i32.store offset=4
    end
    local.get 0
    call 17
    local.get 4)

  (func $__eq_i32 (param i32 i32) (result i32)
    (local i32)
    i32.const 4
    call 4
    local.set 2
    local.get 0
    i32.load
    local.get 1
    i32.load
    i32.eq
    if
      local.get 2
      i32.const 1
      i32.store
    else
      local.get 2
      i32.const 2
      i32.store
    end
    local.get 0
    call 17
    local.get 1
    call 17
    local.get 2)

  (func $__parseInt32 (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i64)
    i32.const 0
    local.set 8
    i64.const 0
    local.set 9
    local.get 0
    i32.load
    local.set 1
    block
      local.get 1
      i32.eqz
      if
        i32.const 1
        local.set 8
        br 1
      end
      i32.const 0
      local.set 2
      i32.const 0
      local.set 3
      local.get 0
      i32.load8_u offset=8
      i32.const 45
      i32.eq
      if
        i32.const 1
        local.set 3
        i32.const 1
        local.set 2
        local.get 1
        i32.const 1
        i32.eq
        if
          i32.const 1
          local.set 8
          br 2
        end
      end
      block
        loop
          local.get 2
          local.get 1
          i32.ge_u
          br_if 1
          local.get 0
          local.get 2
          i32.add
          i32.load8_u offset=8
          local.set 4
          local.get 4
          i32.const 48
          i32.lt_u
          if
            i32.const 1
            local.set 8
            br 3
          end
          local.get 4
          i32.const 57
          i32.gt_u
          if
            i32.const 1
            local.set 8
            br 3
          end
          local.get 9
          i64.const 10
          i64.mul
          local.get 4
          i32.const 48
          i32.sub
          i64.extend_i32_u
          i64.add
          local.set 9
          local.get 9
          i64.const 1
          i64.const 31
          i64.shl
          i64.gt_s
          if
            i32.const 1
            local.set 8
            br 3
          end
          local.get 2
          i32.const 1
          i32.add
          local.set 2
          br 0
        end
      end
      local.get 3
      if
        i64.const 0
        local.get 9
        i64.sub
        local.set 9
      else
        local.get 9
        i64.const 2147483647
        i64.gt_s
        if
          i32.const 1
          local.set 8
          br 2
        end
      end
    end
    local.get 8
    if
      i32.const 4
      call 4
      local.set 7
      local.get 7
      i32.const 22
      i32.store
      i32.const 8
      i32.const 1
      call 15
      local.set 6
      local.get 6
      i32.const 3
      i32.store
      local.get 6
      local.get 7
      i32.store offset=4
    else
      i32.const 4
      call 4
      local.set 5
      local.get 5
      local.get 9
      i32.wrap_i64
      i32.store
      i32.const 8
      i32.const 1
      call 15
      local.set 6
      local.get 6
      i32.const 4
      i32.store
      local.get 6
      local.get 5
      i32.store offset=4
    end
    local.get 0
    call 17
    local.get 6)

  (func $__entryArgEither (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    i32.const 0
    local.set 2
    i32.const 0
    local.set 3
    i32.const 0
    local.set 5
    block
      loop
        local.get 2
        local.get 1
        i32.eq
        br_if 1
        local.get 0
        local.get 2
        i32.add
        i32.load8_u
        local.set 4
        local.get 4
        i32.const 192
        i32.and
        i32.const 128
        i32.ne
        if
          local.get 4
          i32.const 237
          i32.eq
          if
            local.get 0
            local.get 2
            i32.const 1
            i32.add
            i32.add
            i32.load8_u
            i32.const 224
            i32.and
            i32.const 160
            i32.eq
            if
              i32.const 1
              local.set 5
            end
          end
          local.get 4
          i32.const 248
          i32.and
          i32.const 240
          i32.eq
          if
            local.get 3
            i32.const 2
            i32.add
            local.set 3
          else
            local.get 3
            i32.const 1
            i32.add
            local.set 3
          end
          local.get 3
          i32.const 134217728
          i32.gt_u
          br_if 2
        end
        local.get 2
        i32.const 1
        i32.add
        local.set 2
        br 0
      end
    end
    local.get 3
    i32.const 134217728
    i32.gt_u
    if (result i32)
      i32.const 4
      call 4
      local.set 6
      local.get 6
      i32.const 19
      i32.store
      i32.const 8
      i32.const 1
      call 15
      local.set 7
      local.get 7
      i32.const 589989748
      i32.store
      local.get 7
      local.get 6
      i32.store offset=4
      i32.const 8
      i32.const 1
      call 15
      local.set 8
      local.get 8
      i32.const 3
      i32.store
      local.get 8
      local.get 7
      i32.store offset=4
      local.get 8
    else
      local.get 5
      if (result i32)
        i32.const 4
        call 4
        local.set 6
        local.get 6
        i32.const 20
        i32.store
        i32.const 8
        i32.const 1
        call 15
        local.set 7
        local.get 7
        i32.const 502975519
        i32.store
        local.get 7
        local.get 6
        i32.store offset=4
        i32.const 8
        i32.const 1
        call 15
        local.set 8
        local.get 8
        i32.const 3
        i32.store
        local.get 8
        local.get 7
        i32.store offset=4
        local.get 8
      else
        local.get 2
        i32.const 8
        i32.add
        call 4
        local.set 9
        local.get 9
        local.get 2
        i32.store
        local.get 9
        local.get 3
        i32.store offset=4
        local.get 9
        i32.const 8
        i32.add
        local.get 0
        local.get 2
        call 6
        i32.const 8
        i32.const 1
        call 15
        local.set 8
        local.get 8
        i32.const 4
        i32.store
        local.get 8
        local.get 9
        i32.store offset=4
        local.get 8
      end
    end)

  (func $__getArgs (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    i32.const 4
    i32.const 0
    call 15
    local.set 8
    local.get 8
    i32.const 13
    i32.store
    i32.const 12
    i32.const 16
    call 1
    drop
    i32.const 0
    i32.load offset=12
    local.set 0
    local.get 0
    i32.const 2
    i32.ge_u
    if
      i32.const 0
      i32.load offset=16
      call 4
      local.set 2
      local.get 0
      i32.const 4
      i32.mul
      call 4
      local.set 1
      local.get 1
      local.get 2
      call 2
      drop
      local.get 0
      local.set 3
      block
        loop
          local.get 3
          i32.const 1
          i32.le_u
          br_if 1
          local.get 3
          i32.const 1
          i32.sub
          local.set 3
          local.get 1
          local.get 3
          i32.const 4
          i32.mul
          i32.add
          i32.load
          local.set 4
          i32.const 0
          local.set 5
          block
            loop
              local.get 4
              local.get 5
              i32.add
              i32.load8_u
              i32.eqz
              br_if 1
              local.get 5
              i32.const 1
              i32.add
              local.set 5
              br 0
            end
          end
          local.get 4
          local.get 5
          call 13
          local.set 6
          local.get 6
          i32.load
          i32.const 3
          i32.eq
          if
            local.get 6
            return
          end
          local.get 6
          i32.load offset=4
          local.set 7
          local.get 6
          call 5
          i32.const 12
          i32.const 2
          call 15
          local.set 9
          local.get 9
          i32.const 14
          i32.store
          local.get 9
          local.get 7
          i32.store offset=4
          local.get 9
          local.get 8
          i32.store offset=8
          local.get 9
          local.set 8
          br 0
        end
      end
    end
    i32.const 8
    i32.const 1
    call 15
    local.set 6
    local.get 6
    i32.const 4
    i32.store
    local.get 6
    local.get 8
    i32.store offset=4
    local.get 6)

  (func $__alloc_shaped (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    i32.const 1
    i32.const 32
    local.get 0
    i32.const 1
    i32.sub
    i32.clz
    i32.sub
    i32.shl
    local.set 2
    local.get 2
    i32.const 8
    i32.lt_u
    if
      i32.const 8
      local.set 2
    end
    local.get 2
    i32.const 4096
    i32.le_u
    if
      i32.const 24
      local.get 2
      i32.ctz
      i32.const 3
      i32.sub
      i32.const 2
      i32.shl
      i32.add
      local.set 3
      local.get 3
      i32.load
      local.set 4
      local.get 4
      if
        local.get 3
        local.get 4
        i32.const 8
        i32.add
        i32.load
        i32.store
        local.get 4
        i32.const 4
        i32.add
        i32.const 1
        i32.store
        local.get 4
        i32.const 8
        i32.add
        local.get 1
        i32.store
        local.get 4
        i32.const 12
        i32.add
        return
      end
    end
    global.get 0
    i32.const 3
    i32.add
    i32.const -4
    i32.and
    local.set 5
    local.get 5
    i32.const 12
    i32.add
    local.get 2
    i32.add
    global.set 0
    loop
      global.get 0
      memory.size
      i32.const 65536
      i32.mul
      i32.gt_u
      if
        i32.const 1
        memory.grow
        i32.const -1
        i32.eq
        if
          unreachable
        end
        br 1
      end
    end
    local.get 5
    local.get 2
    i32.store
    local.get 5
    i32.const 4
    i32.add
    i32.const 1
    i32.store
    local.get 5
    i32.const 8
    i32.add
    local.get 1
    i32.store
    local.get 5
    i32.const 12
    i32.add)

  (func $__inc_ref (param i32)
    (local i32)
    local.get 0
    i32.const 12
    i32.sub
    i32.load
    local.set 1
    local.get 1
    i32.eqz
    if
      return
    end
    local.get 0
    i32.const 8
    i32.sub
    local.get 0
    i32.const 8
    i32.sub
    i32.load
    i32.const 1
    i32.add
    i32.store)

  (func $__free_recursive (param i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    block
      loop
        local.get 0
        i32.const 12
        i32.sub
        i32.load
        local.set 1
        block
          local.get 1
          i32.eqz
          br_if 0
          local.get 0
          i32.const 8
          i32.sub
          i32.load
          i32.const 1
          i32.sub
          local.set 2
          local.get 0
          i32.const 8
          i32.sub
          local.get 2
          i32.store
          local.get 2
          br_if 0
          local.get 0
          i32.const 4
          i32.sub
          i32.load
          local.set 3
          local.get 3
          i32.eqz
          if
            local.get 0
            call 5
            br 1
          end
          i32.const 1
          local.set 4
          block
            loop
              local.get 4
              local.get 3
              i32.ge_u
              br_if 1
              local.get 0
              local.get 4
              i32.const 2
              i32.shl
              i32.add
              i32.load
              call 18
              local.get 4
              i32.const 1
              i32.add
              local.set 4
              br 0
            end
          end
          local.get 0
          local.get 3
          i32.const 2
          i32.shl
          i32.add
          i32.load
          local.set 4
          local.get 0
          call 5
          local.get 4
          local.set 0
          br 1
        end
        global.get 2
        local.set 5
        local.get 5
        i32.eqz
        br_if 1
        local.get 5
        i32.const 1
        i32.sub
        local.set 5
        local.get 5
        global.set 2
        global.get 1
        local.get 5
        i32.const 2
        i32.shl
        i32.add
        i32.load
        local.set 0
        br 0
      end
    end)

  (func $__free_worklist_push (param i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    global.get 2
    local.set 1
    global.get 3
    local.set 2
    local.get 1
    local.get 2
    i32.eq
    if
      local.get 2
      i32.eqz
      if (result i32)
        i32.const 16
      else
        local.get 2
        i32.const 1
        i32.shl
      end
      local.set 3
      local.get 3
      i32.const 2
      i32.shl
      i32.const 0
      call 15
      local.set 4
      global.get 1
      local.set 5
      i32.const 0
      local.set 6
      block
        loop
          local.get 6
          local.get 1
          i32.ge_u
          br_if 1
          local.get 4
          local.get 6
          i32.const 2
          i32.shl
          i32.add
          local.get 5
          local.get 6
          i32.const 2
          i32.shl
          i32.add
          i32.load
          i32.store
          local.get 6
          i32.const 1
          i32.add
          local.set 6
          br 0
        end
      end
      local.get 5
      if
        local.get 5
        call 5
      end
      local.get 4
      global.set 1
      local.get 3
      global.set 3
    end
    global.get 1
    local.get 1
    i32.const 2
    i32.shl
    i32.add
    local.get 0
    i32.store
    local.get 1
    i32.const 1
    i32.add
    global.set 2)

  (func $v_runIO (param i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 5
      i32.eq
      if (result i32)
        block (result i32)
          local.get 0
          i32.load offset=4
          local.tee 2
          call 16
          local.get 2
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load
        i32.const 7
        i32.eq
        if (result i32)
          local.get 0
          i32.load offset=4
          local.tee 3
          call 16
          local.get 3
          call 7
          local.set 3
          local.get 0
          i32.load offset=8
          local.tee 5
          call 16
          local.get 5
          local.set 4
          local.get 0
          call 17
          local.get 3
          call 17
          local.get 4
          local.set 0
          br 2
        else
          call 14
          local.set 3
          block (result i32)
            i32.const 12
            i32.const 2
            call 15
            local.set 4
            local.get 4
            i32.const 29
            i32.store
            local.get 4
            local.get 0
            i32.load offset=4
            local.tee 5
            call 16
            local.get 5
            i32.store offset=4
            local.get 4
            local.get 3
            i32.store offset=8
            local.get 4
            i32.load offset=8
            call 16
            local.get 4
            i32.const 4
            i32.const 0
            call 15
            local.set 4
            local.get 4
            i32.const 40
            i32.store
            local.get 4
            call 29
            local.set 4
            local.get 3
            call 17
            local.get 4
          end
          local.set 2
          local.get 0
          call 17
          local.get 2
          local.set 0
          br 2
        end
      end
    end)

  (func $v__cps_mklist (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      local.tee 2
      call 16
      local.get 2
      i32.const 0
      call 8
      call 11
      local.set 2
      local.get 2
      i32.load
      i32.const 1
      i32.eq
      if (result i32)
        block (result i32)
          local.get 2
          call 17
          local.get 1
          local.tee 3
          call 16
          local.get 3
          i32.const 4
          i32.const 0
          call 15
          local.set 3
          local.get 3
          i32.const 24
          i32.store
          local.get 3
          call 21
          local.set 3
          local.get 0
          call 17
          local.get 1
          call 17
          local.get 3
        end
      else
        local.get 0
        local.tee 3
        call 16
        local.get 3
        call 10
        local.set 3
        local.get 3
        i32.load
        i32.const 3
        i32.eq
        if (result i32)
          block (result i32)
            local.get 2
            call 17
            local.get 3
            call 17
            local.get 1
            local.tee 5
            call 16
            local.get 5
            i32.const 4
            i32.const 0
            call 15
            local.set 5
            local.get 5
            i32.const 24
            i32.store
            local.get 5
            call 21
            local.set 5
            local.get 0
            call 17
            local.get 1
            call 17
            local.get 5
          end
        else
          local.get 3
          i32.load offset=4
          local.set 4
          local.get 4
          call 16
          local.get 4
          local.set 5
          i32.const 12
          i32.const 2
          call 15
          local.set 7
          local.get 7
          i32.const 33
          i32.store
          local.get 7
          local.get 1
          i32.store offset=4
          local.get 7
          i32.load offset=4
          call 16
          local.get 7
          local.get 0
          i32.store offset=8
          local.get 7
          i32.load offset=8
          call 16
          local.get 7
          local.set 6
          local.get 5
          call 16
          local.get 2
          call 17
          local.get 3
          call 17
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 4
          call 17
          local.get 5
          local.set 0
          local.get 6
          local.set 1
          br 2
        end
      end
    end)

  (func $v__apply_mklist (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 32
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load offset=4
        local.set 2
        local.get 2
        call 16
        local.get 0
        i32.load offset=8
        local.set 3
        local.get 3
        call 16
        local.get 2
        local.set 4
        local.get 0
        i32.load offset=4
        call 17
        local.get 0
        i32.load offset=8
        call 17
        local.get 0
        i32.const 25
        i32.store
        local.get 0
        local.get 3
        i32.store offset=4
        local.get 0
        i32.load offset=4
        call 16
        local.get 0
        local.get 1
        i32.store offset=8
        local.get 0
        i32.load offset=8
        call 16
        local.get 0
        local.set 5
        local.get 4
        call 16
        local.get 1
        call 17
        local.get 3
        call 17
        local.get 2
        call 17
        local.get 4
        local.set 0
        local.get 5
        local.set 1
        br 1
      end
    end)

  (func $v__cps_mkmb (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      local.tee 2
      call 16
      local.get 2
      i32.const 0
      call 8
      call 11
      local.set 2
      local.get 2
      i32.load
      i32.const 1
      i32.eq
      if (result i32)
        block (result i32)
          local.get 2
          call 17
          local.get 1
          local.tee 3
          call 16
          local.get 3
          i32.const 4
          i32.const 0
          call 15
          local.set 3
          local.get 3
          i32.const 11
          i32.store
          local.get 3
          call 23
          local.set 3
          local.get 0
          call 17
          local.get 1
          call 17
          local.get 3
        end
      else
        local.get 0
        local.tee 3
        call 16
        local.get 3
        call 10
        local.set 3
        local.get 3
        i32.load
        i32.const 3
        i32.eq
        if (result i32)
          block (result i32)
            local.get 2
            call 17
            local.get 3
            call 17
            local.get 1
            local.tee 5
            call 16
            local.get 5
            i32.const 4
            i32.const 0
            call 15
            local.set 5
            local.get 5
            i32.const 11
            i32.store
            local.get 5
            call 23
            local.set 5
            local.get 0
            call 17
            local.get 1
            call 17
            local.get 5
          end
        else
          local.get 3
          i32.load offset=4
          local.set 4
          local.get 4
          call 16
          local.get 4
          local.set 5
          i32.const 12
          i32.const 2
          call 15
          local.set 7
          local.get 7
          i32.const 35
          i32.store
          local.get 7
          local.get 1
          i32.store offset=4
          local.get 7
          i32.load offset=4
          call 16
          local.get 7
          local.get 0
          i32.store offset=8
          local.get 7
          i32.load offset=8
          call 16
          local.get 7
          local.set 6
          local.get 5
          call 16
          local.get 2
          call 17
          local.get 3
          call 17
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 4
          call 17
          local.get 5
          local.set 0
          local.get 6
          local.set 1
          br 2
        end
      end
    end)

  (func $v__apply_mkmb (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 34
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load offset=4
        local.set 2
        local.get 2
        call 16
        local.get 1
        i32.load
        i32.const 11
        i32.eq
        if (result i32)
          local.get 2
          local.set 4
          i32.const 8
          i32.const 1
          call 15
          local.set 6
          local.get 6
          i32.const 12
          i32.store
          local.get 6
          local.get 0
          i32.load offset=8
          local.tee 7
          call 16
          local.get 7
          i32.store offset=4
          local.get 6
          local.set 5
          local.get 4
          call 16
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 2
          call 17
          local.get 4
          local.set 0
          local.get 5
          local.set 1
          br 2
        else
          local.get 2
          local.set 5
          local.get 1
          local.set 6
          local.get 5
          call 16
          local.get 6
          call 16
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 2
          call 17
          local.get 5
          local.set 0
          local.get 6
          local.set 1
          br 2
        end
      end
    end)

  (func $v_main (result i32)
    (local i32)
    (local i32)
    i32.const 8
    i32.const 1
    call 15
    local.set 0
    local.get 0
    i32.const 8
    i32.store
    local.get 0
    i32.const 4
    i32.const 0
    call 15
    local.set 1
    local.get 1
    i32.const 28
    i32.store
    local.get 1
    i32.store offset=4
    local.get 0
    i32.const 4
    i32.const 0
    call 15
    local.set 0
    local.get 0
    i32.const 38
    i32.store
    local.get 0
    call 27
    i32.const 4
    i32.const 0
    call 15
    local.set 0
    local.get 0
    i32.const 36
    i32.store
    local.get 0
    call 25)

  (func $v__cps__df_handleErrorIO_0 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 5
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.tee 3
          call 16
          local.get 3
          local.get 0
          local.tee 3
          call 16
          local.get 3
          call 26
          local.set 3
          local.get 0
          call 17
          local.get 1
          call 17
          local.get 3
        end
      else
        local.get 0
        i32.load
        i32.const 6
        i32.eq
        if (result i32)
          block (result i32)
            local.get 1
            local.tee 3
            call 16
            local.get 3
            local.get 0
            i32.load offset=4
            local.tee 3
            call 16
            local.get 3
            local.set 3
            local.get 3
            i32.load
            i32.const 502975519
            i32.eq
            if (result i32)
              local.get 3
              call 17
              i32.const 12
              i32.const 2
              call 15
              local.set 5
              local.get 5
              i32.const 7
              i32.store
              local.get 5
              i32.const 96
              i32.store offset=4
              local.get 5
              i32.const 8
              i32.const 1
              call 15
              local.set 6
              local.get 6
              i32.const 5
              i32.store
              local.get 6
              i32.const 4
              i32.const 0
              call 15
              local.set 7
              local.get 7
              i32.const 0
              i32.store
              local.get 7
              i32.store offset=4
              local.get 6
              i32.store offset=8
              local.get 5
            else
              local.get 3
              call 17
              i32.const 12
              i32.const 2
              call 15
              local.set 5
              local.get 5
              i32.const 7
              i32.store
              local.get 5
              i32.const 124
              i32.store offset=4
              local.get 5
              i32.const 8
              i32.const 1
              call 15
              local.set 6
              local.get 6
              i32.const 5
              i32.store
              local.get 6
              i32.const 4
              i32.const 0
              call 15
              local.set 7
              local.get 7
              i32.const 0
              i32.store
              local.get 7
              i32.store offset=4
              local.get 6
              i32.store offset=8
              local.get 5
            end
            call 26
            local.set 3
            local.get 0
            call 17
            local.get 1
            call 17
            local.get 3
          end
        else
          local.get 0
          i32.load
          i32.const 7
          i32.eq
          if (result i32)
            local.get 0
            i32.load offset=4
            local.set 2
            local.get 2
            call 16
            local.get 0
            i32.load offset=8
            local.set 3
            local.get 3
            call 16
            local.get 3
            local.set 4
            local.get 0
            i32.const 8
            i32.sub
            i32.load
            i32.const 1
            i32.eq
            if (result i32)
              local.get 0
              i32.load offset=4
              call 17
              local.get 0
              i32.load offset=8
              call 17
              local.get 0
              i32.const 37
              i32.store
              local.get 0
              local.get 1
              i32.store offset=4
              local.get 0
              i32.load offset=4
              call 16
              local.get 0
              local.get 2
              i32.store offset=8
              local.get 0
              i32.load offset=8
              call 16
              local.get 0
            else
              i32.const 12
              i32.const 2
              call 15
              local.set 6
              local.get 6
              i32.const 37
              i32.store
              local.get 6
              local.get 1
              i32.store offset=4
              local.get 6
              i32.load offset=4
              call 16
              local.get 6
              local.get 2
              i32.store offset=8
              local.get 6
              i32.load offset=8
              call 16
              local.get 6
              local.get 0
              call 17
            end
            local.set 5
            local.get 4
            call 16
            local.get 1
            call 17
            local.get 3
            call 17
            local.get 2
            call 17
            local.get 4
            local.set 0
            local.get 5
            local.set 1
            br 3
          else
            local.get 0
            i32.load offset=4
            local.set 2
            local.get 2
            call 16
            block (result i32)
              local.get 1
              local.tee 3
              call 16
              local.get 3
              i32.const 8
              i32.const 1
              call 15
              local.set 3
              local.get 3
              i32.const 8
              i32.store
              local.get 3
              i32.const 8
              i32.const 1
              call 15
              local.set 4
              local.get 4
              i32.const 27
              i32.store
              local.get 4
              local.get 2
              i32.store offset=4
              local.get 4
              i32.load offset=4
              call 16
              local.get 4
              i32.store offset=4
              local.get 3
              call 26
              local.set 3
              local.get 2
              call 17
              local.get 0
              call 17
              local.get 1
              call 17
              local.get 3
            end
          end
        end
      end
    end)

  (func $v__apply__df_handleErrorIO_0 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 36
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load offset=4
        local.set 2
        local.get 2
        call 16
        local.get 0
        i32.load offset=8
        local.set 3
        local.get 3
        call 16
        local.get 2
        local.set 4
        local.get 0
        i32.load offset=4
        call 17
        local.get 0
        i32.load offset=8
        call 17
        local.get 0
        i32.const 7
        i32.store
        local.get 0
        local.get 3
        i32.store offset=4
        local.get 0
        i32.load offset=4
        call 16
        local.get 0
        local.get 1
        i32.store offset=8
        local.get 0
        i32.load offset=8
        call 16
        local.get 0
        local.set 5
        local.get 4
        call 16
        local.get 1
        call 17
        local.get 3
        call 17
        local.get 2
        call 17
        local.get 4
        local.set 0
        local.get 5
        local.set 1
        br 1
      end
    end)

  (func $v__cps__df__rowmono_0_andThenIO_4 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 5
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.tee 3
          call 16
          local.get 3
          local.get 0
          i32.load offset=4
          local.tee 3
          call 16
          local.get 3
          local.set 3
          block (result i32)
            local.get 3
            i32.load
            i32.const 13
            i32.eq
            if (result i32)
              i32.const 3
              call 8
            else
              local.get 3
              i32.load offset=4
              local.tee 6
              call 16
              local.get 6
              call 12
              local.set 6
              local.get 6
              i32.load
              i32.const 3
              i32.eq
              if (result i32)
                local.get 6
                call 17
                i32.const 4
                call 8
              else
                local.get 6
                i32.load offset=4
                local.set 7
                local.get 7
                call 16
                local.get 6
                call 17
                block (result i32)
                  local.get 7
                  local.set 8
                  local.get 8
                  call 16
                  local.get 7
                  call 17
                  local.get 8
                end
              end
            end
            local.set 4
            block (result i32)
              i32.const 12
              i32.const 2
              call 15
              local.set 5
              local.get 5
              i32.const 7
              i32.store
              local.get 5
              block
                block
                  local.get 4
                  local.tee 8
                  call 16
                  local.get 8
                  i32.const 5
                  call 8
                  call 11
                  local.set 8
                  local.get 8
                  i32.load
                  i32.const 1
                  i32.eq
                  if (result i32)
                    local.get 8
                    call 17
                    i32.const 4
                    i32.const 0
                    call 15
                    local.set 9
                    local.get 9
                    i32.const 11
                    i32.store
                    local.get 9
                  else
                    local.get 8
                    call 17
                    local.get 4
                    local.tee 9
                    call 16
                    local.get 9
                    i32.const 4
                    i32.const 0
                    call 15
                    local.set 9
                    local.get 9
                    i32.const 34
                    i32.store
                    local.get 9
                    call 22
                  end
                  local.set 8
                  local.get 8
                  i32.load
                  i32.const 11
                  i32.eq
                  if
                    local.get 8
                    call 17
                    i32.const 9
                    call 8
                    local.set 6
                    br 2
                  else
                    local.get 8
                    i32.load offset=4
                    local.set 9
                    local.get 9
                    call 16
                    local.get 8
                    call 17
                    local.get 9
                    local.tee 10
                    call 16
                    local.get 10
                    i32.const 4
                    i32.const 0
                    call 15
                    local.set 10
                    local.get 10
                    i32.const 32
                    i32.store
                    local.get 10
                    call 20
                    local.set 7
                    local.get 9
                    call 17
                    br 1
                  end
                end
                local.get 7
                i32.load
                i32.const 24
                i32.eq
                if (result i32)
                  i32.const 0
                  call 8
                else
                  local.get 7
                  i32.load offset=4
                  local.tee 10
                  call 16
                  local.get 10
                end
                local.set 6
                local.get 7
                call 17
              end
              local.get 6
              call 9
              i32.store offset=4
              local.get 5
              i32.const 8
              i32.const 1
              call 15
              local.set 6
              local.get 6
              i32.const 5
              i32.store
              local.get 6
              i32.const 4
              i32.const 0
              call 15
              local.set 7
              local.get 7
              i32.const 0
              i32.store
              local.get 7
              i32.store offset=4
              local.get 6
              i32.store offset=8
              local.get 5
              local.set 5
              local.get 4
              call 17
              local.get 5
            end
            local.set 4
            local.get 3
            call 17
            local.get 4
          end
          call 28
          local.set 3
          local.get 0
          call 17
          local.get 1
          call 17
          local.get 3
        end
      else
        local.get 0
        i32.load
        i32.const 6
        i32.eq
        if (result i32)
          block (result i32)
            local.get 1
            local.tee 3
            call 16
            local.get 3
            local.get 0
            local.tee 3
            call 16
            local.get 3
            call 28
            local.set 3
            local.get 0
            call 17
            local.get 1
            call 17
            local.get 3
          end
        else
          local.get 0
          i32.load
          i32.const 7
          i32.eq
          if (result i32)
            local.get 0
            i32.load offset=4
            local.set 2
            local.get 2
            call 16
            local.get 0
            i32.load offset=8
            local.set 3
            local.get 3
            call 16
            local.get 3
            local.set 4
            local.get 0
            i32.const 8
            i32.sub
            i32.load
            i32.const 1
            i32.eq
            if (result i32)
              local.get 0
              i32.load offset=4
              call 17
              local.get 0
              i32.load offset=8
              call 17
              local.get 0
              i32.const 39
              i32.store
              local.get 0
              local.get 1
              i32.store offset=4
              local.get 0
              i32.load offset=4
              call 16
              local.get 0
              local.get 2
              i32.store offset=8
              local.get 0
              i32.load offset=8
              call 16
              local.get 0
            else
              i32.const 12
              i32.const 2
              call 15
              local.set 6
              local.get 6
              i32.const 39
              i32.store
              local.get 6
              local.get 1
              i32.store offset=4
              local.get 6
              i32.load offset=4
              call 16
              local.get 6
              local.get 2
              i32.store offset=8
              local.get 6
              i32.load offset=8
              call 16
              local.get 6
              local.get 0
              call 17
            end
            local.set 5
            local.get 4
            call 16
            local.get 1
            call 17
            local.get 3
            call 17
            local.get 2
            call 17
            local.get 4
            local.set 0
            local.get 5
            local.set 1
            br 3
          else
            local.get 0
            i32.load offset=4
            local.set 2
            local.get 2
            call 16
            block (result i32)
              local.get 1
              local.tee 3
              call 16
              local.get 3
              i32.const 8
              i32.const 1
              call 15
              local.set 3
              local.get 3
              i32.const 8
              i32.store
              local.get 3
              i32.const 8
              i32.const 1
              call 15
              local.set 4
              local.get 4
              i32.const 26
              i32.store
              local.get 4
              local.get 2
              i32.store offset=4
              local.get 4
              i32.load offset=4
              call 16
              local.get 4
              i32.store offset=4
              local.get 3
              call 28
              local.set 3
              local.get 2
              call 17
              local.get 0
              call 17
              local.get 1
              call 17
              local.get 3
            end
          end
        end
      end
    end)

  (func $v__apply__df__rowmono_0_andThenIO_4 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 38
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load offset=4
        local.set 2
        local.get 2
        call 16
        local.get 0
        i32.load offset=8
        local.set 3
        local.get 3
        call 16
        local.get 2
        local.set 4
        local.get 0
        i32.load offset=4
        call 17
        local.get 0
        i32.load offset=8
        call 17
        local.get 0
        i32.const 7
        i32.store
        local.get 0
        local.get 3
        i32.store offset=4
        local.get 0
        i32.load offset=4
        call 16
        local.get 0
        local.get 1
        i32.store offset=8
        local.get 0
        i32.load offset=8
        call 16
        local.get 0
        local.set 5
        local.get 4
        call 16
        local.get 1
        call 17
        local.get 3
        call 17
        local.get 2
        call 17
        local.get 4
        local.set 0
        local.get 5
        local.set 1
        br 1
      end
    end)

  (func $v__cps__scc__apply1__df__lam_14_5__df__lam_9_1 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 29
      i32.eq
      if (result i32)
        local.get 0
        i32.load offset=4
        local.set 2
        local.get 2
        call 16
        local.get 0
        i32.load offset=8
        local.set 3
        local.get 3
        call 16
        local.get 2
        i32.load
        i32.const 26
        i32.eq
        if (result i32)
          local.get 0
          i32.load offset=4
          call 17
          local.get 0
          i32.const 30
          i32.store
          local.get 0
          local.get 2
          i32.load offset=4
          local.tee 7
          call 16
          local.get 7
          i32.store offset=4
          local.get 0
          local.set 5
          local.get 1
          local.set 6
          local.get 6
          call 16
          local.get 1
          call 17
          local.get 3
          call 17
          local.get 2
          call 17
          local.get 5
          local.set 0
          local.get 6
          local.set 1
          br 2
        else
          local.get 2
          i32.load
          i32.const 27
          i32.eq
          if (result i32)
            local.get 0
            i32.load offset=4
            call 17
            local.get 0
            i32.const 31
            i32.store
            local.get 0
            local.get 2
            i32.load offset=4
            local.tee 7
            call 16
            local.get 7
            i32.store offset=4
            local.get 0
            local.set 5
            local.get 1
            local.set 6
            local.get 6
            call 16
            local.get 1
            call 17
            local.get 3
            call 17
            local.get 2
            call 17
            local.get 5
            local.set 0
            local.get 6
            local.set 1
            br 3
          else
            block (result i32)
              local.get 1
              local.tee 4
              call 16
              local.get 4
              local.get 3
              i32.load
              i32.const 3
              i32.eq
              if (result i32)
                i32.const 8
                i32.const 1
                call 15
                local.set 5
                local.get 5
                i32.const 6
                i32.store
                local.get 5
                local.get 3
                i32.load offset=4
                local.tee 6
                call 16
                local.get 6
                i32.store offset=4
                local.get 5
              else
                i32.const 8
                i32.const 1
                call 15
                local.set 5
                local.get 5
                i32.const 5
                i32.store
                local.get 5
                local.get 3
                i32.load offset=4
                local.tee 6
                call 16
                local.get 6
                i32.store offset=4
                local.get 5
              end
              call 30
              local.set 4
              local.get 3
              call 17
              local.get 2
              call 17
              local.get 0
              call 17
              local.get 1
              call 17
              local.get 4
            end
          end
        end
      else
        local.get 0
        i32.load
        i32.const 30
        i32.eq
        if (result i32)
          local.get 0
          i32.load offset=4
          local.set 2
          local.get 2
          call 16
          local.get 0
          i32.load offset=8
          local.set 3
          local.get 3
          call 16
          local.get 0
          i32.const 29
          i32.store
          local.get 0
          local.set 4
          i32.const 8
          i32.const 1
          call 15
          local.set 6
          local.get 6
          i32.const 41
          i32.store
          local.get 6
          local.get 1
          i32.store offset=4
          local.get 6
          i32.load offset=4
          call 16
          local.get 6
          local.set 5
          local.get 1
          call 17
          local.get 3
          call 17
          local.get 2
          call 17
          local.get 4
          local.set 0
          local.get 5
          local.set 1
          br 2
        else
          local.get 0
          i32.load offset=4
          local.set 2
          local.get 2
          call 16
          local.get 0
          i32.load offset=8
          local.set 3
          local.get 3
          call 16
          local.get 0
          i32.const 29
          i32.store
          local.get 0
          local.set 4
          i32.const 8
          i32.const 1
          call 15
          local.set 6
          local.get 6
          i32.const 42
          i32.store
          local.get 6
          local.get 1
          i32.store offset=4
          local.get 6
          i32.load offset=4
          call 16
          local.get 6
          local.set 5
          local.get 1
          call 17
          local.get 3
          call 17
          local.get 2
          call 17
          local.get 4
          local.set 0
          local.get 5
          local.set 1
          br 2
        end
      end
    end)

  (func $v__apply__scc__apply1__df__lam_14_5__df__lam_9_1 (param i32 i32) (result i32)
    (local i32)
    (local i32)
    (local i32)
    (local i32)
    loop (result i32)
      local.get 0
      i32.load
      i32.const 40
      i32.eq
      if (result i32)
        block (result i32)
          local.get 1
          local.set 2
          local.get 0
          call 17
          local.get 2
        end
      else
        local.get 0
        i32.load
        i32.const 41
        i32.eq
        if (result i32)
          local.get 0
          i32.load offset=4
          local.tee 5
          call 16
          local.get 5
          local.set 3
          local.get 1
          local.tee 5
          call 16
          local.get 5
          i32.const 4
          i32.const 0
          call 15
          local.set 5
          local.get 5
          i32.const 38
          i32.store
          local.get 5
          call 27
          local.set 4
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 3
          local.set 0
          local.get 4
          local.set 1
          br 2
        else
          local.get 0
          i32.load offset=4
          local.tee 5
          call 16
          local.get 5
          local.set 3
          local.get 1
          local.tee 5
          call 16
          local.get 5
          i32.const 4
          i32.const 0
          call 15
          local.set 5
          local.get 5
          i32.const 36
          i32.store
          local.get 5
          call 25
          local.set 4
          local.get 1
          call 17
          local.get 0
          call 17
          local.get 3
          local.set 0
          local.get 4
          local.set 1
          br 2
        end
      end
    end)

  (func $_start
    call 24
    call 19
    drop)
)