;; Awsum WASM codegen — WAT text format for inspection.
;; Binary .wasm is generated by assembleWASM for execution.
(module

  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $args_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_get" (func $args_get (param i32 i32) (result i32)))

  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 70))
  (data (i32.const 64) "\00")
  (data (i32.const 65) "done\00")
  (table 2 funcref)
  (elem (i32.const 0) $v_countDown $v_main)

  (func $__strlen (param $s i32) (result i32)
    (local $len i32)
    (local.set $len (i32.const 0))
    (block $break
      (loop $loop
        (br_if $break (i32.eqz (i32.load8_u (i32.add (local.get $s) (local.get $len)))))
        (local.set $len (i32.add (local.get $len) (i32.const 1)))
        (br $loop)))
    (local.get $len))


  (func $__alloc (param $size i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (i32.and (i32.add (global.get $heap) (i32.const 3)) (i32.const -4)))
    (global.set $heap (i32.add (local.get $ptr) (local.get $size)))
    (if (i32.gt_u (global.get $heap) (i32.mul (memory.size) (i32.const 65536)))
      (then (drop (memory.grow (i32.const 1)))))
    (local.get $ptr))


  (func $__memcpy (param $dst i32) (param $src i32) (param $len i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $break
      (loop $loop
        (br_if $break (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8 (i32.add (local.get $dst) (local.get $i))
                    (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))


  (func $__print (param $s i32) (result i32)
    (local $len i32)
    (local.set $len (call $__strlen (local.get $s)))
    (i32.store (i32.const 0) (local.get $s))
    (i32.store (i32.const 4) (local.get $len))
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 8)))
    (i32.const 0))


  (func $__box_i32 (param $v i32) (result i32)
    (local $p i32)
    (local.set $p (call $__alloc (i32.const 4)))
    (i32.store (local.get $p) (local.get $v))
    (local.get $p))


  (func $__predInt32 (param $p i32) (result i32)
    (local $v i32) (local $ue i32) (local $box i32) (local $cell i32)
    (local.set $v (i32.load (local.get $p)))
    (if (result i32) (i32.eq (local.get $v) (i32.const -2147483648))
      (then
        (local.set $ue (call $__alloc (i32.const 4)))
        (i32.store (local.get $ue) (i32.const 0))
        (local.set $cell (call $__alloc (i32.const 8)))
        (i32.store (local.get $cell) (i32.const 0))
        (i32.store offset=4 (local.get $cell) (local.get $ue))
        (local.get $cell))
      (else
        (local.set $box (call $__alloc (i32.const 4)))
        (i32.store (local.get $box) (i32.sub (local.get $v) (i32.const 1)))
        (local.set $cell (call $__alloc (i32.const 8)))
        (i32.store (local.get $cell) (i32.const 1))
        (i32.store offset=4 (local.get $cell) (local.get $box))
        (local.get $cell))))


  (func $__eq_i32 (param $a i32) (param $b i32) (result i32)
    (local $cell i32)
    (local.set $cell (call $__alloc (i32.const 4)))
    (if (result i32) (i32.eq (i32.load (local.get $a)) (i32.load (local.get $b)))
      (then
        (i32.store (local.get $cell) (i32.const 0))
        (local.get $cell))
      (else
        (i32.store (local.get $cell) (i32.const 1))
        (local.get $cell))))


  (func $__get_arg (result i32)
    (local $argv_buf i32) (local $ptrs i32)
    (drop (call $args_sizes_get (i32.const 12) (i32.const 16)))
    (if (result i32) (i32.lt_u (i32.load (i32.const 12)) (i32.const 2))
      (then (i32.const 64))
      (else
        (local.set $argv_buf (call $__alloc (i32.load (i32.const 16))))
        (local.set $ptrs (call $__alloc (i32.mul (i32.load (i32.const 12)) (i32.const 4))))
        (drop (call $args_get (local.get $ptrs) (local.get $argv_buf)))
        (i32.load (i32.add (local.get $ptrs) (i32.const 4))))))

  (func $v_countDown (export "v_countDown") (param $v_n i32) (param $v_acc i32) (result i32)
    (local $__scrut i32)
    (local $__k0 i32)
    (local $__k1 i32)
    (loop $tco_top (result i32) (block (result i32) (local.set $__scrut (call $__eq_i32 (local.get $v_n) (call $__box_i32 (i32.const 0)))) (if (result i32) (i32.eq (i32.load (local.get $__scrut)) (i32.const 0)) (then (local.get $v_acc)) (else (block (result i32) (local.set $__scrut (call $__predInt32 (local.get $v_n))) (if (result i32) (i32.eq (i32.load (local.get $__scrut)) (i32.const 0)) (then (local.get $v_acc)) (else (local.set $__k0 (i32.load offset=4 (local.get $__scrut))) (local.set $__k1 (local.get $v_acc)) (local.set $v_n (local.get $__k0)) (local.set $v_acc (local.get $__k1)) (br $tco_top)))))))))

  (func $v_start (export "v_start") (result i32)
    (call $__box_i32 (i32.const 100000)))

  (func $v_main (export "v_main") (param $v__input i32) (result i32)
    (call $__print (call $v_countDown (call $v_start) (i32.const 65))))

  (func $_start (export "_start")
    (drop (call $v_main (call $__get_arg))))

)