-- | Unified WASM instruction IR — the single source of truth behind both WASM
--   projections. One 'WasmFunc' value — a flat list of 'WasmInstr' with
--   operands carried *symbolically* (function refs by name, never an index) —
--   feeds two total, decision-free projections, so they cannot diverge on
--   "which function" a call denotes:
--
--     * 'renderWat' here, which prints the WAT text.
--     * 'Awsum.Codegen.WASM.Assemble.assembleFunc', which resolves the symbolic
--       call targets to function indices and emits the code-section bytes.
--
--   The IR is /linear/ and /numeric/ — it matches WASM's true (post-folding)
--   structure: explicit @block@/@loop@/@if@/@end@, @br@ by numeric depth,
--   @local.get N@ / @call N@ by index. The rendered @.wat@ is therefore the
--   plain (unfolded) text form, which honestly shows what the @.wasm@ bytes run,
--   rather than the folded s-expression sugar.
module Awsum.Codegen.WASM.Instr
  ( ValType (..),
    BlockType (..),
    MemArg (..),
    WasmInstr (..),
    WasmFunc (..),
    renderValType,
    renderWat,
    boxI32Spec,
    incRefSpec,
    freeRecursiveSpec,
    freeWorklistPushSpec,
    freeSpec,
    memcpySpec,
    predI32Spec,
    predU8Spec,
    predU32Spec,
    succI32Spec,
    succU8Spec,
    succU32Spec,
    eqI32Spec,
    negI32Spec,
    addI32Spec,
    addU8Spec,
    addU32Spec,
    subI32Spec,
    subU8Spec,
    subU32Spec,
    mulI32Spec,
    mulU8Spec,
    mulU32Spec,
    showI32Spec,
    showU32Spec,
    memcmpSpec,
    eqStringSpec,
    allocSpec,
    allocShapedSpec,
    lengthUtf8BytesSpec,
    lengthCodePointsSpec,
    lengthUtf16CodeUnitsSpec,
    utf16OfRangeSpec,
    concatSpec,
    printSpec,
    getArgsSpec,
    stdinReadAllSpec,
    entryArgEitherSpec,
    parseInt32Spec,
    parseUInt8Spec,
    parseUInt32Spec,
    splitOnFirstSpec,
  )
where

import Awsum.Core (PreludeTags (..))
import Awsum.HM (rowTag)
import Awsum.Syntax (Type' (..), noSpan)
import Data.Map.Strict qualified as Map
import Data.Text qualified as T
import Relude

-- | A WASM value type (the subset Awsum's codegen uses — all values are @i32@
--   pointers; @i64@ appears only inside a few arithmetic helpers).
data ValType = I32 | I64
  deriving stock (Eq, Show)

-- | A structured-control block's result type. WASM blocks/loops/ifs either
--   produce nothing (@BtVoid@ = 0x40) or a single @i32@ / @i64@.
data BlockType = BtVoid | BtI32 | BtI64
  deriving stock (Eq, Show)

-- | A memory access immediate: alignment (as the binary log2 exponent — 2 means
--   4-byte natural alignment for @i32@) and a byte offset. Awsum's accesses are
--   always naturally aligned, so the text omits @align@ and only prints a
--   non-zero @offset@.
data MemArg = MemArg
  { maAlign :: Int,
    maOffset :: Int
  }
  deriving stock (Eq, Show)

-- | One abstract WASM instruction. Operands are symbolic where the two
--   projections would otherwise diverge: a call carries the callee's /name/, not
--   its function index.
data WasmInstr
  = I32Const Int
  | -- | @call@ a sibling function by name; the assembler resolves it to a
    --   function index through the shared name→index map, and the text renders
    --   the same numeric index.
    Call Text
  | -- | @call@ a function by its already-resolved numeric index. User-code
    --   emission works from @ecFuncIdx@ (indices, not names), so it uses this
    --   directly; encodes and renders exactly like 'Call' after name lookup.
    CallIdx Int
  | -- | @call_indirect (type N)@ through table 0 — the post-@LowerClosures@
    --   @$applyN@ dispatch for residual higher-order calls. Carries the type
    --   index; the table index is always @0@.
    CallIndirect Int
  | LocalGet Int
  | LocalSet Int
  | LocalTee Int
  | -- | Module globals, addressed by numeric index (globals live in their own
    --   index space, not the function space, so they stay numeric rather than
    --   symbolic). Awsum uses four: @0@ heap bump pointer, @1@ free-worklist
    --   buffer, @2@ free-worklist top, @3@ free-worklist capacity.
    GlobalGet Int
  | GlobalSet Int
  | I32Load MemArg
  | I32Store MemArg
  | -- | Single-byte memory access (unsigned-extended load / truncating store);
    --   used by @__memcpy@. Natural alignment is @0@ (@MemArg 0 _@).
    I32Load8U MemArg
  | I32Store8 MemArg
  | -- | Structured control. @Block@/@Loop@/@If@ open a nesting level closed by a
    --   matching 'End'; 'Br'/'BrIf' jump out by relative depth (0 = innermost
    --   enclosing block). 'If' consumes the top-of-stack i32 condition; 'Else'
    --   splits its arms. The 'BlockType' is the value left on the stack
    --   (@BtVoid@ for none — the common case for these control wrappers).
    Block BlockType
  | Loop BlockType
  | If BlockType
  | Else
  | End
  | Br Int
  | BrIf Int
  | -- | Early return from the enclosing function.
    Return
  | -- | Trap. @__alloc_shaped@ reaches it only if @memory.grow@ fails (OOM).
    Unreachable
  | -- | Discard the top-of-stack value. @__print@ drops the @fd_write@ result.
    Drop
  | I32Add
  | I32Sub
  | I32Mul
  | -- | Unsigned division / remainder — the @show@ helpers extract decimal
    --   digits with @i32.div_u@ / @i32.rem_u@ by 10.
    I32DivU
  | I32RemU
  | I32And
  | I32Xor
  | I32Shl
  | I32Eqz
  | I32Eq
  | I32Ne
  | I32LtS
  | I32LtU
  | I32GeS
  | I32GeU
  | I32GtU
  | I32LeU
  | -- | Count trailing / leading zero bits — @__free@ derives a size-class bin
    --   index from a power-of-two rounded size with @i32.ctz@; @__alloc_shaped@
    --   rounds a request up to the next power-of-two bin with @i32.clz@.
    I32Ctz
  | I32Clz
  | -- | 64-bit arithmetic + i32↔i64 conversions. The overflow-checking integer
    --   helpers (@__addInt32@, @__mulInt32@, …) widen both operands to @i64@,
    --   do the op without loss, then range-check before truncating back: e.g.
    --   @i64.extend_i32_s@ the inputs, @i64.mul@, compare against the i32 bounds
    --   as @i64@ constants, and @i32.wrap_i64@ the result on the in-range arm.
    I64Const Int
  | I64Add
  | I64Sub
  | I64Mul
  | I64Shl
  | I64LtS
  | I64GtS
  | I64GtU
  | I32WrapI64
  | I64ExtendI32S
  | I64ExtendI32U
  | -- | Linear-memory size / grow, in 64 KiB pages. Both carry the single
    --   memory index @0@ as an implicit immediate (emitted as a @0x00@ byte).
    --   @__alloc_shaped@ uses them to extend the heap when a bin is empty.
    MemorySize
  | MemoryGrow
  deriving stock (Eq, Show)

-- | A function: name (a readable @$label@ in the WAT header — it never reaches
--   the code-section bytes), parameter and result types, the extra locals
--   (beyond the params), and the linear body. Both projections share these, so
--   the WAT @(func …)@ header and the binary type/locals declarations cannot
--   disagree.
data WasmFunc = WasmFunc
  { wfName :: Text,
    wfParams :: [ValType],
    wfResults :: [ValType],
    wfLocals :: [ValType],
    wfBody :: [WasmInstr]
  }
  deriving stock (Eq, Show)

renderValType :: ValType -> Text
renderValType I32 = "i32"
renderValType I64 = "i64"

-- | Plain (unfolded) WAT text for a function: a @(func $name (param …)(result …)
--   (local …) <body>)@ with the body as a flat instruction listing — one per
--   line, references numeric. Mirrors the byte projection 1:1.
renderWat :: Map Text Word32 -> WasmFunc -> Text
renderWat idxMap f =
  T.intercalate "\n" (header : locals <> body) <> ")"
  where
    header =
      "  (func $"
        <> wfName f
        <> grp "param" (wfParams f)
        <> grp "result" (wfResults f)
    grp _ [] = ""
    grp kw vts = " (" <> kw <> " " <> unwords (map renderValType vts) <> ")"
    locals = ["    (local " <> renderValType vt <> ")" | vt <- wfLocals f]
    body = map (("    " <>) . renderInstr idxMap) (wfBody f)

renderInstr :: Map Text Word32 -> WasmInstr -> Text
renderInstr idxMap = \case
  I32Const n -> "i32.const " <> show n
  Call name -> "call " <> show (lookupIdx name)
  CallIdx idx -> "call " <> show idx
  CallIndirect ty -> "call_indirect (type " <> show ty <> ")"
  LocalGet n -> "local.get " <> show n
  LocalSet n -> "local.set " <> show n
  LocalTee n -> "local.tee " <> show n
  GlobalGet n -> "global.get " <> show n
  GlobalSet n -> "global.set " <> show n
  I32Load m -> "i32.load" <> memArgSuffix m
  I32Store m -> "i32.store" <> memArgSuffix m
  I32Load8U m -> "i32.load8_u" <> memArgSuffix m
  I32Store8 m -> "i32.store8" <> memArgSuffix m
  Block bt -> "block" <> blockTypeSuffix bt
  Loop bt -> "loop" <> blockTypeSuffix bt
  If bt -> "if" <> blockTypeSuffix bt
  Else -> "else"
  End -> "end"
  Br n -> "br " <> show n
  BrIf n -> "br_if " <> show n
  Return -> "return"
  Unreachable -> "unreachable"
  Drop -> "drop"
  I32Add -> "i32.add"
  I32Sub -> "i32.sub"
  I32Mul -> "i32.mul"
  I32DivU -> "i32.div_u"
  I32RemU -> "i32.rem_u"
  I32And -> "i32.and"
  I32Xor -> "i32.xor"
  I32Shl -> "i32.shl"
  I32Eqz -> "i32.eqz"
  I32Eq -> "i32.eq"
  I32Ne -> "i32.ne"
  I32LtS -> "i32.lt_s"
  I32LtU -> "i32.lt_u"
  I32GeS -> "i32.ge_s"
  I32GeU -> "i32.ge_u"
  I32GtU -> "i32.gt_u"
  I32LeU -> "i32.le_u"
  I32Ctz -> "i32.ctz"
  I32Clz -> "i32.clz"
  I64Const n -> "i64.const " <> show n
  I64Add -> "i64.add"
  I64Sub -> "i64.sub"
  I64Mul -> "i64.mul"
  I64Shl -> "i64.shl"
  I64LtS -> "i64.lt_s"
  I64GtS -> "i64.gt_s"
  I64GtU -> "i64.gt_u"
  I32WrapI64 -> "i32.wrap_i64"
  I64ExtendI32S -> "i64.extend_i32_s"
  I64ExtendI32U -> "i64.extend_i32_u"
  MemorySize -> "memory.size"
  MemoryGrow -> "memory.grow"
  where
    lookupIdx name = fromMaybe (error ("WASM.Instr: no index for " <> name)) (Map.lookup name idxMap)

-- | A memory access prints only its non-default operands: natural alignment and
--   a zero offset are the assumed defaults, matching the bytes (a @0@ offset is
--   still encoded, but the text omits it for legibility).
memArgSuffix :: MemArg -> Text
memArgSuffix (MemArg _ o) = if o /= 0 then " offset=" <> show o else ""

-- | A structured block's result annotation, plain-WAT form. @BtVoid@ prints
--   nothing (the byte is @0x40@); a value type prints @(result …)@.
blockTypeSuffix :: BlockType -> Text
blockTypeSuffix = \case
  BtVoid -> ""
  BtI32 -> " (result i32)"
  BtI64 -> " (result i64)"

-- ════════════════════════════════════════════════════════════════════════════
-- Function specs
-- ════════════════════════════════════════════════════════════════════════════

-- | FNV-1a 32-bit row tags for the prelude's @OverflowError@ / @UnderflowError@
--   labels, the @CRow@ box tag of the @Left@ the overflow-checking arithmetic
--   helpers build. Computed via 'rowTag' (= @Awsum.HM.canonicalLabel@) so they
--   stay in lockstep with the user-side @CRowCase@ comparison without magic
--   numbers. Program-independent, so the spec computes them rather than taking
--   them as parameters. Stored as 'Int' here; 'asmInstr' truncates to the same
--   @Int32@ bit pattern the binary's @encodeSLEB128@ sees, and the value printed
--   by 'renderWat' matches the text codegen's @show (rowTag …)@.
overflowRowTag :: Int
overflowRowTag = fromIntegral (rowTag (TyCon noSpan "OverflowError"))

underflowRowTag :: Int
underflowRowTag = fromIntegral (rowTag (TyCon noSpan "UnderflowError"))

-- | FNV-1a 32-bit row tags for the two input-decoding error labels the
--   @__entryArgEither@ helper produces. Same role as 'overflowRowTag' — the
--   @CRow@ box tag of the @Left@ — kept as 'Word32' (the type 'rowTag' returns)
--   to mirror the source; 'asmInstr' truncates to the matching @Int32@ pattern.
stringTooLongTagWord :: Word32
stringTooLongTagWord = rowTag (TyCon noSpan "StringTooLong")

unpairedSurrogateTagWord :: Word32
unpairedSurrogateTagWord = rowTag (TyCon noSpan "UnpairedUtf16Surrogate")

-- | @__box_i32@: allocate a 4-byte cell and store the value into it — the
--   pointer is the boxed @i32@. Branchless leaf helper. Local 0 is the param
--   @v@; local 1 is the cell pointer @p@.
boxI32Spec :: WasmFunc
boxI32Spec =
  WasmFunc
    { wfName = "__box_i32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32],
      wfBody =
        [ I32Const 4,
          Call "__alloc",
          LocalSet 1,
          LocalGet 1,
          LocalGet 0,
          I32Store (MemArg 2 0),
          LocalGet 1
        ]
    }

-- | @__inc_ref@: bump the refcount of a heap cell. Reads the @flag@ word at
--   @p - 12@; a @0@ flag marks a data-section literal (no refcount), so the
--   helper returns early. Otherwise it increments the refcount word at @p - 8@
--   in place. Void result. Local 0 is the param @p@; local 1 is @flag@.
incRefSpec :: WasmFunc
incRefSpec =
  WasmFunc
    { wfName = "__inc_ref",
      wfParams = [I32],
      wfResults = [],
      wfLocals = [I32],
      wfBody =
        [ -- flag = load (p - 12)
          LocalGet 0,
          I32Const 12,
          I32Sub,
          I32Load (MemArg 2 0),
          LocalSet 1,
          -- if flag == 0: return (literal, no refcount)
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          Return,
          End,
          -- store (p - 8) := load (p - 8) + 1
          LocalGet 0,
          I32Const 8,
          I32Sub,
          LocalGet 0,
          I32Const 8,
          I32Sub,
          I32Load (MemArg 2 0),
          I32Const 1,
          I32Add,
          I32Store (MemArg 2 0)
        ]
    }

-- | @__free_recursive@: drop a cell's refcount; on reaching zero, return it to
--   its freelist bin and cascade into its children. Iterative — an explicit
--   worklist (the @__wl_*@ globals) and a tail-jump @loop@ keep system-stack use
--   O(1) regardless of cascade depth (Awsum's acyclic, immutable cell graph
--   guarantees termination). Void result. Param @p@ at slot 0; locals 1=@flag@,
--   2=@rc@, 3=@shape@, 4=@i@/child-temp, 5=@top@.
freeRecursiveSpec :: WasmFunc
freeRecursiveSpec =
  WasmFunc
    { wfName = "__free_recursive",
      wfParams = [I32],
      wfResults = [],
      wfLocals = [I32, I32, I32, I32, I32],
      wfBody =
        [ Block BtVoid,
          Loop BtVoid,
          LocalGet 0,
          I32Const 12,
          I32Sub,
          I32Load (MemArg 2 0),
          LocalSet 1,
          Block BtVoid,
          LocalGet 1,
          I32Eqz,
          BrIf 0,
          LocalGet 0,
          I32Const 8,
          I32Sub,
          I32Load (MemArg 2 0),
          I32Const 1,
          I32Sub,
          LocalSet 2,
          LocalGet 0,
          I32Const 8,
          I32Sub,
          LocalGet 2,
          I32Store (MemArg 2 0),
          LocalGet 2,
          BrIf 0,
          LocalGet 0,
          I32Const 4,
          I32Sub,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 3,
          I32Eqz,
          If BtVoid,
          LocalGet 0,
          Call "__free",
          Br 1,
          End,
          I32Const 1,
          LocalSet 4,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 4,
          LocalGet 3,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 4,
          I32Const 2,
          I32Shl,
          I32Add,
          I32Load (MemArg 2 0),
          Call "__free_worklist_push",
          LocalGet 4,
          I32Const 1,
          I32Add,
          LocalSet 4,
          Br 0,
          End,
          End,
          LocalGet 0,
          LocalGet 3,
          I32Const 2,
          I32Shl,
          I32Add,
          I32Load (MemArg 2 0),
          LocalSet 4,
          LocalGet 0,
          Call "__free",
          LocalGet 4,
          LocalSet 0,
          Br 1,
          End,
          GlobalGet 2,
          LocalSet 5,
          LocalGet 5,
          I32Eqz,
          BrIf 1,
          LocalGet 5,
          I32Const 1,
          I32Sub,
          LocalSet 5,
          LocalGet 5,
          GlobalSet 2,
          GlobalGet 1,
          LocalGet 5,
          I32Const 2,
          I32Shl,
          I32Add,
          I32Load (MemArg 2 0),
          LocalSet 0,
          Br 0,
          End,
          End
        ]
    }

-- | @__free_worklist_push@: append @p@ to the free-worklist buffer, growing it
--   (16 entries, doubling) when full. On grow, buffers that still fit a size
--   class are returned via @__free@; larger ones leak (bounded by 2x current
--   capacity). Void result. Param @p@ at slot 0; locals 1=@top@, 2=@cap@,
--   3=@new_cap@, 4=@new_buf@, 5=@old_buf@, 6=@i@.
freeWorklistPushSpec :: WasmFunc
freeWorklistPushSpec =
  WasmFunc
    { wfName = "__free_worklist_push",
      wfParams = [I32],
      wfResults = [],
      wfLocals = [I32, I32, I32, I32, I32, I32],
      wfBody =
        [ GlobalGet 2,
          LocalSet 1,
          GlobalGet 3,
          LocalSet 2,
          LocalGet 1,
          LocalGet 2,
          I32Eq,
          If BtVoid,
          LocalGet 2,
          I32Eqz,
          If BtI32,
          I32Const 16,
          Else,
          LocalGet 2,
          I32Const 1,
          I32Shl,
          End,
          LocalSet 3,
          LocalGet 3,
          I32Const 2,
          I32Shl,
          I32Const 0,
          Call "__alloc_shaped",
          LocalSet 4,
          GlobalGet 1,
          LocalSet 5,
          I32Const 0,
          LocalSet 6,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 6,
          LocalGet 1,
          I32GeU,
          BrIf 1,
          LocalGet 4,
          LocalGet 6,
          I32Const 2,
          I32Shl,
          I32Add,
          LocalGet 5,
          LocalGet 6,
          I32Const 2,
          I32Shl,
          I32Add,
          I32Load (MemArg 2 0),
          I32Store (MemArg 2 0),
          LocalGet 6,
          I32Const 1,
          I32Add,
          LocalSet 6,
          Br 0,
          End,
          End,
          LocalGet 5,
          If BtVoid,
          LocalGet 5,
          Call "__free",
          End,
          LocalGet 4,
          GlobalSet 1,
          LocalGet 3,
          GlobalSet 3,
          End,
          GlobalGet 1,
          LocalGet 1,
          I32Const 2,
          I32Shl,
          I32Add,
          LocalGet 0,
          I32Store (MemArg 2 0),
          LocalGet 1,
          I32Const 1,
          I32Add,
          GlobalSet 2
        ]
    }

-- | @__free@: push a heap cell back onto its size-class freelist. Literals
--   (@flag == 0@) and oversize blocks (@flag > 4096@) are dropped on the floor.
--   The bin index is derived from the power-of-two size class via @i32.ctz@.
--   Void result. Param @p@ at slot 0; locals 1=@flag@, 2=@bin@, 3=@head@.
freeSpec :: WasmFunc
freeSpec =
  WasmFunc
    { wfName = "__free",
      wfParams = [I32],
      wfResults = [],
      wfLocals = [I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Const 12,
          I32Sub,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          Return,
          End,
          LocalGet 1,
          I32Const 4096,
          I32GtU,
          If BtVoid,
          Return,
          End,
          I32Const 24,
          LocalGet 1,
          I32Ctz,
          I32Const 3,
          I32Sub,
          I32Const 2,
          I32Shl,
          I32Add,
          LocalSet 2,
          LocalGet 2,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 0,
          I32Const 4,
          I32Sub,
          LocalGet 3,
          I32Store (MemArg 2 0),
          LocalGet 2,
          LocalGet 0,
          I32Const 12,
          I32Sub,
          I32Store (MemArg 2 0)
        ]
    }

-- | @__memcpy(dst, src, len)@: byte-wise forward copy. Void result. Params
--   0=@dst@, 1=@src@, 2=@len@; local 3=@i@.
memcpySpec :: WasmFunc
memcpySpec =
  WasmFunc
    { wfName = "__memcpy",
      wfParams = [I32, I32, I32],
      wfResults = [],
      wfLocals = [I32],
      wfBody =
        [ I32Const 0,
          LocalSet 3,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 3,
          LocalGet 2,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 3,
          I32Add,
          LocalGet 1,
          LocalGet 3,
          I32Add,
          I32Load8U (MemArg 0 0),
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Add,
          LocalSet 3,
          Br 0,
          End,
          End
        ]
    }

-- | @__predInt32@: @Int32 -> Either UnderflowError Int32@. @Left UnderflowError@
--   at @INT32_MIN@, else @Right (v - 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
predI32Spec :: PreludeTags -> WasmFunc
predI32Spec tags =
  WasmFunc
    { wfName = "__predInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Const (-2147483648),
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Sub,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__predUInt8@: @UInt8 -> Either UnderflowError UInt8@. @Left@ at @0@, else @Right (v - 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
predU8Spec :: PreludeTags -> WasmFunc
predU8Spec tags =
  WasmFunc
    { wfName = "__predUInt8",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Sub,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__predUInt32@: @UInt32 -> Either UnderflowError UInt32@. @Left@ at @0@, else @Right (v - 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
predU32Spec :: PreludeTags -> WasmFunc
predU32Spec tags =
  WasmFunc
    { wfName = "__predUInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Sub,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__succInt32@: @Int32 -> Either OverflowError Int32@. @Left OverflowError@
--   at @INT32_MAX@, else @Right (v + 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
succI32Spec :: PreludeTags -> WasmFunc
succI32Spec tags =
  WasmFunc
    { wfName = "__succInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Const 2147483647,
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Add,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__succUInt8@: @UInt8 -> Either OverflowError UInt8@. @Left@ at @255@, else @Right (v + 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
succU8Spec :: PreludeTags -> WasmFunc
succU8Spec tags =
  WasmFunc
    { wfName = "__succUInt8",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Const 255,
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Add,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__succUInt32@: @UInt32 -> Either OverflowError UInt32@. @Left@ at @UINT32_MAX@, else @Right (v + 1)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
succU32Spec :: PreludeTags -> WasmFunc
succU32Spec tags =
  WasmFunc
    { wfName = "__succUInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Const (-1),
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          LocalGet 1,
          I32Const 1,
          I32Add,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__eq_i32@: structural equality of two boxed integers into a nullary @Bool@ cell
--   (@ptTrue@ / @ptFalse@). Shared by @eqInt32@ / @eqUInt8@ / @eqUInt32@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
eqI32Spec :: PreludeTags -> WasmFunc
eqI32Spec tags =
  WasmFunc
    { wfName = "__eq_i32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32],
      wfBody =
        [ I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 0,
          I32Load (MemArg 2 0),
          LocalGet 1,
          I32Load (MemArg 2 0),
          I32Eq,
          If BtVoid,
          LocalGet 2,
          I32Const (ptTrue tags),
          I32Store (MemArg 2 0),
          Else,
          LocalGet 2,
          I32Const (ptFalse tags),
          I32Store (MemArg 2 0),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 2
        ]
    }

-- | @__negInt32@: @Int32 -> Either OverflowError Int32@. @Left OverflowError@ at
--   @INT32_MIN@ (whose negation overflows), else @Right (0 - v)@. Tag-parameterised; result @Either@/@Bool@ cell pointer.
negI32Spec :: PreludeTags -> WasmFunc
negI32Spec tags =
  WasmFunc
    { wfName = "__negInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          LocalGet 1,
          I32Const (-2147483648),
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const 0,
          LocalGet 1,
          I32Sub,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 4,
          LocalGet 3,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__addInt32@: @Int32 -> Int32 -> Either OverflowError Int32@. Signed-overflow via
--   the @(a^s)&(b^s) < 0@ i32 trick (no i64 needed); 3-level @Left@ on overflow. Tag+row-parameterised.
addI32Spec :: PreludeTags -> WasmFunc
addI32Spec tags =
  WasmFunc
    { wfName = "__addInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          LocalSet 4,
          LocalGet 2,
          LocalGet 4,
          I32Xor,
          LocalGet 3,
          LocalGet 4,
          I32Xor,
          I32And,
          I32Const 0,
          I32LtS,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 5,
          LocalGet 5,
          LocalGet 2,
          I32Const 0,
          I32GeS,
          If BtI32,
          I32Const (ptOverflowError tags),
          Else,
          I32Const (ptUnderflowError tags),
          End,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          LocalGet 2,
          I32Const 0,
          I32GeS,
          If BtI32,
          I32Const overflowRowTag,
          Else,
          I32Const underflowRowTag,
          End,
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 5,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 6,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 7,
          LocalGet 7,
          LocalGet 4,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 7,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 8
        ]
    }

-- | @__addUInt8@: @UInt8 -> UInt8 -> Either OverflowError UInt8@. @Left@ when sum @> 255@. Tag+row-parameterised.
addU8Spec :: PreludeTags -> WasmFunc
addU8Spec tags =
  WasmFunc
    { wfName = "__addUInt8",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalGet 1,
          I32Load (MemArg 2 0),
          I32Add,
          LocalSet 2,
          LocalGet 2,
          I32Const 255,
          I32GtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__addUInt32@: @UInt32 -> UInt32 -> Either OverflowError UInt32@. i64-widened sum,
--   @Left@ when @> UINT32_MAX@. Local 0 (slot 2) is the @i64@ sum. Tag+row-parameterised.
addU32Spec :: PreludeTags -> WasmFunc
addU32Spec tags =
  WasmFunc
    { wfName = "__addUInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I64, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          I64ExtendI32U,
          LocalGet 1,
          I32Load (MemArg 2 0),
          I64ExtendI32U,
          I64Add,
          LocalSet 2,
          LocalGet 2,
          I64Const 4294967295,
          I64GtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32WrapI64,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__subInt32@: @Int32 -> Int32 -> Either UnderflowError/OverflowError Int32@. Signed
--   over/underflow check; 3-level @Left@. Tag+row-parameterised.
subI32Spec :: PreludeTags -> WasmFunc
subI32Spec tags =
  WasmFunc
    { wfName = "__subInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 2,
          LocalGet 3,
          I32Sub,
          LocalSet 4,
          LocalGet 2,
          LocalGet 3,
          I32Xor,
          LocalGet 2,
          LocalGet 4,
          I32Xor,
          I32And,
          I32Const 0,
          I32LtS,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 5,
          LocalGet 5,
          LocalGet 2,
          I32Const 0,
          I32GeS,
          If BtI32,
          I32Const (ptOverflowError tags),
          Else,
          I32Const (ptUnderflowError tags),
          End,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          LocalGet 2,
          I32Const 0,
          I32GeS,
          If BtI32,
          I32Const overflowRowTag,
          Else,
          I32Const underflowRowTag,
          End,
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 5,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 6,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 7,
          LocalGet 7,
          LocalGet 4,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 7,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 8
        ]
    }

-- | @__subUInt8@: @UInt8 -> UInt8 -> Either UnderflowError UInt8@. @Left@ when @a < b@. Tag+row-parameterised.
subU8Spec :: PreludeTags -> WasmFunc
subU8Spec tags =
  WasmFunc
    { wfName = "__subUInt8",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalGet 1,
          I32Load (MemArg 2 0),
          I32Sub,
          LocalSet 2,
          LocalGet 2,
          I32Const 0,
          I32LtS,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__subUInt32@: @UInt32 -> UInt32 -> Either UnderflowError UInt32@. @Left@ when @a < b@. Tag+row-parameterised.
subU32Spec :: PreludeTags -> WasmFunc
subU32Spec tags =
  WasmFunc
    { wfName = "__subUInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 2,
          LocalGet 3,
          I32LtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 4,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 5,
          LocalGet 5,
          LocalGet 2,
          LocalGet 3,
          I32Sub,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 5,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 6
        ]
    }

-- | @__mulInt32@: @Int32 -> Int32 -> Either OverflowError Int32@. i64-widened signed product,
--   range-checked against the @Int32@ bounds. Local 0 (slot 2) is the @i64@ product. Tag+row-parameterised.
mulI32Spec :: PreludeTags -> WasmFunc
mulI32Spec tags =
  WasmFunc
    { wfName = "__mulInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I64, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          I64ExtendI32S,
          LocalGet 1,
          I32Load (MemArg 2 0),
          I64ExtendI32S,
          I64Mul,
          LocalSet 2,
          LocalGet 2,
          I64Const 2147483647,
          I64GtS,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const overflowRowTag,
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 3,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 6,
          I32Store (MemArg 2 4),
          Else,
          LocalGet 2,
          I64Const (-2147483648),
          I64LtS,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptUnderflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const underflowRowTag,
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 3,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 6,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32WrapI64,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__mulUInt8@: @UInt8 -> UInt8 -> Either OverflowError UInt8@. @Left@ when product @> 255@. Tag+row-parameterised.
mulU8Spec :: PreludeTags -> WasmFunc
mulU8Spec tags =
  WasmFunc
    { wfName = "__mulUInt8",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalGet 1,
          I32Load (MemArg 2 0),
          I32Mul,
          LocalSet 2,
          LocalGet 2,
          I32Const 255,
          I32GtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__mulUInt32@: @UInt32 -> UInt32 -> Either OverflowError UInt32@. i64-widened product,
--   @Left@ when @> UINT32_MAX@. Local 0 (slot 2) is the @i64@ product. Tag+row-parameterised.
mulU32Spec :: PreludeTags -> WasmFunc
mulU32Spec tags =
  WasmFunc
    { wfName = "__mulUInt32",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I64, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          I64ExtendI32U,
          LocalGet 1,
          I32Load (MemArg 2 0),
          I64ExtendI32U,
          I64Mul,
          LocalSet 2,
          LocalGet 2,
          I64Const 4294967295,
          I64GtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 3,
          LocalGet 3,
          I32Const (ptOverflowError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32WrapI64,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__show_i32@: render a boxed @Int32@ to its decimal @String@ (sign + digits via
--   @i32.rem_u@/@i32.div_u@ by 10 into a scratch buffer, then @__memcpy@ into the
--   final string cell). Shared by @showInt32@ / @showUInt8@.
showI32Spec :: WasmFunc
showI32Spec =
  WasmFunc
    { wfName = "__show_i32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          I32Const 24,
          Call "__alloc",
          LocalSet 2,
          I32Const 23,
          LocalSet 3,
          LocalGet 1,
          I32Const 0,
          I32LtS,
          If BtVoid,
          I32Const 1,
          LocalSet 4,
          I32Const 0,
          LocalGet 1,
          I32Sub,
          LocalSet 5,
          Else,
          I32Const 0,
          LocalSet 4,
          LocalGet 1,
          LocalSet 5,
          End,
          LocalGet 5,
          I32Eqz,
          If BtVoid,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          I32Const 48,
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          Else,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 5,
          I32Eqz,
          BrIf 1,
          LocalGet 5,
          I32Const 10,
          I32RemU,
          LocalSet 6,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          LocalGet 6,
          I32Const 48,
          I32Add,
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          LocalGet 5,
          I32Const 10,
          I32DivU,
          LocalSet 5,
          Br 0,
          End,
          End,
          End,
          LocalGet 4,
          If BtVoid,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          I32Const 45,
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          End,
          I32Const 23,
          LocalGet 3,
          I32Sub,
          LocalSet 7,
          LocalGet 2,
          I32Const 8,
          I32Add,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          I32Const 1,
          I32Add,
          LocalGet 7,
          Call "__memcpy",
          LocalGet 2,
          LocalGet 7,
          I32Store (MemArg 2 0),
          LocalGet 2,
          LocalGet 7,
          I32Store (MemArg 2 4),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 2
        ]
    }

-- | @__show_u32@: render a boxed @UInt32@ to its decimal @String@ (unsigned digit
--   loop; no sign). Same buffer-then-@__memcpy@ shape as @__show_i32@.
showU32Spec :: WasmFunc
showU32Spec =
  WasmFunc
    { wfName = "__show_u32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          I32Const 24,
          Call "__alloc",
          LocalSet 2,
          I32Const 23,
          LocalSet 3,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          I32Const 48,
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          Else,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 1,
          I32Eqz,
          BrIf 1,
          LocalGet 1,
          I32Const 10,
          I32RemU,
          LocalSet 4,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          LocalGet 4,
          I32Const 48,
          I32Add,
          I32Store8 (MemArg 0 0),
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          LocalGet 1,
          I32Const 10,
          I32DivU,
          LocalSet 1,
          Br 0,
          End,
          End,
          End,
          I32Const 23,
          LocalGet 3,
          I32Sub,
          LocalSet 4,
          LocalGet 2,
          I32Const 8,
          I32Add,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          I32Const 1,
          I32Add,
          LocalGet 4,
          Call "__memcpy",
          LocalGet 2,
          LocalGet 4,
          I32Store (MemArg 2 0),
          LocalGet 2,
          LocalGet 4,
          I32Store (MemArg 2 4),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 2
        ]
    }

-- | @__memcmp(a, b, len)@: 1 iff all @len@ bytes at @a@ and @b@ agree, 0 on first
--   mismatch (early @return@). Drives @__eqString@ after the length check.
memcmpSpec :: WasmFunc
memcmpSpec =
  WasmFunc
    { wfName = "__memcmp",
      wfParams = [I32, I32, I32],
      wfResults = [I32],
      wfLocals = [I32],
      wfBody =
        [ I32Const 0,
          LocalSet 3,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 3,
          LocalGet 2,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 3,
          I32Add,
          I32Load8U (MemArg 0 0),
          LocalGet 1,
          LocalGet 3,
          I32Add,
          I32Load8U (MemArg 0 0),
          I32Ne,
          If BtVoid,
          I32Const 0,
          Return,
          End,
          LocalGet 3,
          I32Const 1,
          I32Add,
          LocalSet 3,
          Br 0,
          End,
          End,
          I32Const 1
        ]
    }

-- | @__eqString@: structural @String@ equality into a nullary @Bool@ cell — compare
--   byte counts, then @__memcmp@ the payloads; @ptTrue@ / @ptFalse@.
eqStringSpec :: PreludeTags -> WasmFunc
eqStringSpec tags =
  WasmFunc
    { wfName = "__eqString",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 2,
          LocalGet 3,
          I32Eq,
          If BtVoid,
          LocalGet 0,
          I32Const 8,
          I32Add,
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 2,
          Call "__memcmp",
          LocalSet 5,
          LocalGet 5,
          If BtVoid,
          LocalGet 4,
          I32Const (ptTrue tags),
          I32Store (MemArg 2 0),
          Else,
          LocalGet 4,
          I32Const (ptFalse tags),
          I32Store (MemArg 2 0),
          End,
          Else,
          LocalGet 4,
          I32Const (ptFalse tags),
          I32Store (MemArg 2 0),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__alloc(size)@: thin wrapper over @__alloc_shaped(size, 0)@ — scalars / strings /\n--   nullary cells keep the default @shape = 0@.
allocSpec :: WasmFunc
allocSpec =
  WasmFunc
    { wfName = "__alloc",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [],
      wfBody =
        [ LocalGet 0,
          I32Const 0,
          Call "__alloc_shaped"
        ]
    }

-- | @__alloc_shaped(size, shape)@: the freelist allocator. Rounds @size@ up to a\n--   power-of-two bin (min 8) via @i32.clz@; pops a free block from the size-class\n--   bin (heads at linear offsets 24..63) re-initialising its 12-byte header, else\n--   bump-allocates and grows linear memory in 64 KiB pages (trap on OOM). Stores\n--   @shape@ at @block+8@. Slots: 0=size 1=shape; 2=rounded 3=bin_addr 4=head 5=ptr.
allocShapedSpec :: WasmFunc
allocShapedSpec =
  WasmFunc
    { wfName = "__alloc_shaped",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32],
      wfBody =
        [ I32Const 1,
          I32Const 32,
          LocalGet 0,
          I32Const 1,
          I32Sub,
          I32Clz,
          I32Sub,
          I32Shl,
          LocalSet 2,
          LocalGet 2,
          I32Const 8,
          I32LtU,
          If BtVoid,
          I32Const 8,
          LocalSet 2,
          End,
          LocalGet 2,
          I32Const 4096,
          I32LeU,
          If BtVoid,
          I32Const 24,
          LocalGet 2,
          I32Ctz,
          I32Const 3,
          I32Sub,
          I32Const 2,
          I32Shl,
          I32Add,
          LocalSet 3,
          LocalGet 3,
          I32Load (MemArg 2 0),
          LocalSet 4,
          LocalGet 4,
          If BtVoid,
          LocalGet 3,
          LocalGet 4,
          I32Const 8,
          I32Add,
          I32Load (MemArg 2 0),
          I32Store (MemArg 2 0),
          LocalGet 4,
          I32Const 4,
          I32Add,
          I32Const 1,
          I32Store (MemArg 2 0),
          LocalGet 4,
          I32Const 8,
          I32Add,
          LocalGet 1,
          I32Store (MemArg 2 0),
          LocalGet 4,
          I32Const 12,
          I32Add,
          Return,
          End,
          End,
          GlobalGet 0,
          I32Const 3,
          I32Add,
          I32Const (-4),
          I32And,
          LocalSet 5,
          LocalGet 5,
          I32Const 12,
          I32Add,
          LocalGet 2,
          I32Add,
          GlobalSet 0,
          Loop BtVoid,
          GlobalGet 0,
          MemorySize,
          I32Const 65536,
          I32Mul,
          I32GtU,
          If BtVoid,
          I32Const 1,
          MemoryGrow,
          I32Const (-1),
          I32Eq,
          If BtVoid,
          Unreachable,
          End,
          Br 1,
          End,
          End,
          LocalGet 5,
          LocalGet 2,
          I32Store (MemArg 2 0),
          LocalGet 5,
          I32Const 4,
          I32Add,
          I32Const 1,
          I32Store (MemArg 2 0),
          LocalGet 5,
          I32Const 8,
          I32Add,
          LocalGet 1,
          I32Store (MemArg 2 0),
          LocalGet 5,
          I32Const 12,
          I32Add
        ]
    }

-- | @__lengthUtf8Bytes@: @String -> Int32@ — the stored UTF-8 byte count (header\n--   word at @s+0@), boxed.
lengthUtf8BytesSpec :: WasmFunc
lengthUtf8BytesSpec =
  WasmFunc
    { wfName = "__lengthUtf8Bytes",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32],
      wfBody =
        [ I32Const 4,
          Call "__alloc",
          LocalSet 1,
          LocalGet 1,
          LocalGet 0,
          I32Load (MemArg 2 0),
          I32Store (MemArg 2 0),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1
        ]
    }

-- | @__lengthCodePoints@: @String -> Int32@ — count bytes whose top two bits are not\n--   @10@ (i.e. non-continuation bytes = code points), boxed.
lengthCodePointsSpec :: WasmFunc
lengthCodePointsSpec =
  WasmFunc
    { wfName = "__lengthCodePoints",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 5,
          LocalGet 0,
          I32Const 8,
          I32Add,
          LocalSet 6,
          I32Const 0,
          LocalSet 1,
          I32Const 0,
          LocalSet 2,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 1,
          LocalGet 5,
          I32GeU,
          BrIf 1,
          LocalGet 6,
          LocalGet 1,
          I32Add,
          I32Load8U (MemArg 0 0),
          LocalSet 3,
          LocalGet 3,
          I32Const 192,
          I32And,
          I32Const 128,
          I32Ne,
          If BtVoid,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          End,
          LocalGet 1,
          I32Const 1,
          I32Add,
          LocalSet 1,
          Br 0,
          End,
          End,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 2,
          I32Store (MemArg 2 0),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 4
        ]
    }

-- | @__lengthUtf16CodeUnits@: @String -> Int32@ — the stored UTF-16 code-unit count\n--   (header word at @s+4@), boxed.
lengthUtf16CodeUnitsSpec :: WasmFunc
lengthUtf16CodeUnitsSpec =
  WasmFunc
    { wfName = "__lengthUtf16CodeUnits",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32],
      wfBody =
        [ I32Const 4,
          Call "__alloc",
          LocalSet 1,
          LocalGet 1,
          LocalGet 0,
          I32Load (MemArg 2 4),
          I32Store (MemArg 2 0),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1
        ]
    }

-- | @__utf16_of_range(payload, byteLen)@: count the UTF-16 code units a UTF-8 byte\n--   range decodes to (4-byte sequences = 2 units, else 1). Used by @__splitOnFirst@.
utf16OfRangeSpec :: WasmFunc
utf16OfRangeSpec =
  WasmFunc
    { wfName = "__utf16_of_range",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32],
      wfBody =
        [ I32Const 0,
          LocalSet 2,
          I32Const 0,
          LocalSet 3,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 2,
          LocalGet 1,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Load8U (MemArg 0 0),
          LocalSet 4,
          LocalGet 4,
          I32Const 192,
          I32And,
          I32Const 128,
          I32Ne,
          If BtVoid,
          LocalGet 4,
          I32Const 248,
          I32And,
          I32Const 240,
          I32Eq,
          If BtVoid,
          LocalGet 3,
          I32Const 2,
          I32Add,
          LocalSet 3,
          Else,
          LocalGet 3,
          I32Const 1,
          I32Add,
          LocalSet 3,
          End,
          End,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          LocalGet 3
        ]
    }

-- | @__concat(a, b)@: @String -> String -> Either StringTooLong String@. Sums byte\n--   counts, @Left StringTooLong@ past the runtime cap, else allocates the joined\n--   cell and @__memcpy@s both payloads; @ptLeft@ / @ptRight@.
concatSpec :: PreludeTags -> WasmFunc
concatSpec tags =
  WasmFunc
    { wfName = "__concat",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 0,
          I32Load (MemArg 2 4),
          LocalSet 4,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          LocalGet 1,
          I32Load (MemArg 2 4),
          LocalSet 5,
          LocalGet 4,
          LocalGet 5,
          I32Add,
          LocalSet 6,
          LocalGet 6,
          I32Const 134217728,
          I32GtU,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptStringTooLong tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 9,
          LocalGet 9,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 9,
          LocalGet 8,
          I32Store (MemArg 2 4),
          Else,
          LocalGet 2,
          LocalGet 3,
          I32Add,
          LocalSet 7,
          LocalGet 7,
          I32Const 8,
          I32Add,
          Call "__alloc",
          LocalSet 10,
          LocalGet 10,
          LocalGet 7,
          I32Store (MemArg 2 0),
          LocalGet 10,
          LocalGet 6,
          I32Store (MemArg 2 4),
          LocalGet 10,
          I32Const 8,
          I32Add,
          LocalGet 0,
          I32Const 8,
          I32Add,
          LocalGet 2,
          Call "__memcpy",
          LocalGet 10,
          I32Const 8,
          I32Add,
          LocalGet 2,
          I32Add,
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 3,
          Call "__memcpy",
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 9,
          LocalGet 9,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 9,
          LocalGet 10,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 9
        ]
    }

-- | @__print(s)@: write a @String@'s UTF-8 payload to stdout via the WASI @fd_write@\n--   host import (scratch iovec at addr 0), discard the result, and return @Unit@.
printSpec :: PreludeTags -> WasmFunc
printSpec tags =
  WasmFunc
    { wfName = "__print",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          I32Const 0,
          LocalGet 0,
          I32Const 8,
          I32Add,
          I32Store (MemArg 2 0),
          I32Const 0,
          LocalGet 1,
          I32Store (MemArg 2 4),
          I32Const 1,
          I32Const 0,
          I32Const 1,
          I32Const 8,
          Call "fd_write",
          Drop,
          I32Const 4,
          Call "__alloc",
          LocalSet 2,
          LocalGet 2,
          I32Const (ptUnit tags),
          I32Store (MemArg 2 0),
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 2
        ]
    }

-- | @__getArgs@: read @argv@ via WASI @args_sizes_get@/@args_get@, decode each as UTF-8\n--   (@__entryArgEither@), and build @Either (decode-error) (List String)@. All-or-nothing:\n--   any element's @Left@ short-circuits. Tags @ptNil@/@ptCons@/@ptLeft@/@ptRight@.
getArgsSpec :: PreludeTags -> WasmFunc
getArgsSpec tags =
  WasmFunc
    { wfName = "__getArgs",
      wfParams = [],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ I32Const 4,
          I32Const 0,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptNil tags),
          I32Store (MemArg 2 0),
          I32Const 12,
          I32Const 16,
          Call "args_sizes_get",
          Drop,
          I32Const 0,
          I32Load (MemArg 2 12),
          LocalSet 0,
          LocalGet 0,
          I32Const 2,
          I32GeU,
          If BtVoid,
          I32Const 0,
          I32Load (MemArg 2 16),
          Call "__alloc",
          LocalSet 2,
          LocalGet 0,
          I32Const 4,
          I32Mul,
          Call "__alloc",
          LocalSet 1,
          LocalGet 1,
          LocalGet 2,
          Call "args_get",
          Drop,
          LocalGet 0,
          LocalSet 3,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 3,
          I32Const 1,
          I32LeU,
          BrIf 1,
          LocalGet 3,
          I32Const 1,
          I32Sub,
          LocalSet 3,
          LocalGet 1,
          LocalGet 3,
          I32Const 4,
          I32Mul,
          I32Add,
          I32Load (MemArg 2 0),
          LocalSet 4,
          I32Const 0,
          LocalSet 5,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 4,
          LocalGet 5,
          I32Add,
          I32Load8U (MemArg 0 0),
          I32Eqz,
          BrIf 1,
          LocalGet 5,
          I32Const 1,
          I32Add,
          LocalSet 5,
          Br 0,
          End,
          End,
          LocalGet 4,
          LocalGet 5,
          Call "__entryArgEither",
          LocalSet 6,
          LocalGet 6,
          I32Load (MemArg 2 0),
          I32Const (ptLeft tags),
          I32Eq,
          If BtVoid,
          LocalGet 6,
          Return,
          End,
          LocalGet 6,
          I32Load (MemArg 2 4),
          LocalSet 7,
          LocalGet 6,
          Call "__free",
          I32Const 12,
          I32Const 2,
          Call "__alloc_shaped",
          LocalSet 9,
          LocalGet 9,
          I32Const (ptCons tags),
          I32Store (MemArg 2 0),
          LocalGet 9,
          LocalGet 7,
          I32Store (MemArg 2 4),
          LocalGet 9,
          LocalGet 8,
          I32Store (MemArg 2 8),
          LocalGet 9,
          LocalSet 8,
          Br 0,
          End,
          End,
          End,
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 8,
          I32Store (MemArg 2 4),
          LocalGet 6
        ]
    }

-- | @__stdinReadAll@: read stdin to EOF via WASI @fd_read@ into a growing buffer\n--   (@__memcpy@ on grow), then decode the bytes via @__entryArgEither@.
stdinReadAllSpec :: WasmFunc
stdinReadAllSpec =
  WasmFunc
    { wfName = "__stdinReadAll",
      wfParams = [],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ I32Const 4096,
          LocalSet 1,
          LocalGet 1,
          Call "__alloc",
          LocalSet 0,
          I32Const 0,
          LocalSet 2,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 1,
          LocalGet 2,
          I32Sub,
          LocalSet 3,
          LocalGet 3,
          I32Const 4096,
          I32LtU,
          If BtVoid,
          LocalGet 1,
          I32Const 2,
          I32Mul,
          LocalSet 5,
          LocalGet 5,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 0,
          LocalGet 2,
          Call "__memcpy",
          LocalGet 4,
          LocalSet 0,
          LocalGet 5,
          LocalSet 1,
          LocalGet 1,
          LocalGet 2,
          I32Sub,
          LocalSet 3,
          End,
          I32Const 16,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Store (MemArg 2 0),
          I32Const 20,
          LocalGet 3,
          I32Store (MemArg 2 0),
          I32Const 0,
          I32Const 16,
          I32Const 1,
          I32Const 12,
          Call "fd_read",
          Drop,
          I32Const 0,
          I32Load (MemArg 2 12),
          LocalSet 6,
          LocalGet 6,
          I32Eqz,
          BrIf 1,
          LocalGet 2,
          LocalGet 6,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Const 0,
          I32Store8 (MemArg 0 0),
          LocalGet 0,
          LocalGet 2,
          Call "__entryArgEither"
        ]
    }

-- | @__entryArgEither(payload, byteLen)@: validate a UTF-8 byte range and build the\n--   string cell, or @Left StringTooLong@/@Left UnpairedUtf16Surrogate@ on failure.\n--   Shared by @__getArgs@ and @__stdinReadAll@; the source of both decode errors.
entryArgEitherSpec :: PreludeTags -> WasmFunc
entryArgEitherSpec tags =
  WasmFunc
    { wfName = "__entryArgEither",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ I32Const 0,
          LocalSet 2,
          I32Const 0,
          LocalSet 3,
          I32Const 0,
          LocalSet 5,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 2,
          LocalGet 1,
          I32Eq,
          BrIf 1,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Load8U (MemArg 0 0),
          LocalSet 4,
          LocalGet 4,
          I32Const 192,
          I32And,
          I32Const 128,
          I32Ne,
          If BtVoid,
          LocalGet 4,
          I32Const 237,
          I32Eq,
          If BtVoid,
          LocalGet 0,
          LocalGet 2,
          I32Const 1,
          I32Add,
          I32Add,
          I32Load8U (MemArg 0 0),
          I32Const 224,
          I32And,
          I32Const 160,
          I32Eq,
          If BtVoid,
          I32Const 1,
          LocalSet 5,
          End,
          End,
          LocalGet 4,
          I32Const 248,
          I32And,
          I32Const 240,
          I32Eq,
          If BtVoid,
          LocalGet 3,
          I32Const 2,
          I32Add,
          LocalSet 3,
          Else,
          LocalGet 3,
          I32Const 1,
          I32Add,
          LocalSet 3,
          End,
          LocalGet 3,
          I32Const 134217728,
          I32GtU,
          BrIf 2,
          End,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          LocalGet 3,
          I32Const 134217728,
          I32GtU,
          If BtI32,
          I32Const 4,
          Call "__alloc",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptStringTooLong tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 7,
          LocalGet 7,
          I32Const (fromIntegral stringTooLongTagWord),
          I32Store (MemArg 2 0),
          LocalGet 7,
          LocalGet 6,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 7,
          I32Store (MemArg 2 4),
          LocalGet 8,
          Else,
          LocalGet 5,
          If BtI32,
          I32Const 4,
          Call "__alloc",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptUnpairedUtf16Surrogate tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 7,
          LocalGet 7,
          I32Const (fromIntegral unpairedSurrogateTagWord),
          I32Store (MemArg 2 0),
          LocalGet 7,
          LocalGet 6,
          I32Store (MemArg 2 4),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 7,
          I32Store (MemArg 2 4),
          LocalGet 8,
          Else,
          LocalGet 2,
          I32Const 8,
          I32Add,
          Call "__alloc",
          LocalSet 9,
          LocalGet 9,
          LocalGet 2,
          I32Store (MemArg 2 0),
          LocalGet 9,
          LocalGet 3,
          I32Store (MemArg 2 4),
          LocalGet 9,
          I32Const 8,
          I32Add,
          LocalGet 0,
          LocalGet 2,
          Call "__memcpy",
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 8,
          LocalGet 8,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 8,
          LocalGet 9,
          I32Store (MemArg 2 4),
          LocalGet 8,
          End,
          End
        ]
    }

-- | @__parseInt32@: @String -> Either ParseError Int32@. Optional sign + decimal\n--   digits accumulated in an @i64@ (slot 9) with range-checks against the @Int32@\n--   bounds; @Left ParseError@ on any non-digit / overflow / empty.
parseInt32Spec :: PreludeTags -> WasmFunc
parseInt32Spec tags =
  WasmFunc
    { wfName = "__parseInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32, I64],
      wfBody =
        [ I32Const 0,
          LocalSet 8,
          I64Const 0,
          LocalSet 9,
          LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          Block BtVoid,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 1,
          End,
          I32Const 0,
          LocalSet 2,
          I32Const 0,
          LocalSet 3,
          LocalGet 0,
          I32Load8U (MemArg 0 8),
          I32Const 45,
          I32Eq,
          If BtVoid,
          I32Const 1,
          LocalSet 3,
          I32Const 1,
          LocalSet 2,
          LocalGet 1,
          I32Const 1,
          I32Eq,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 2,
          End,
          End,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 2,
          LocalGet 1,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Load8U (MemArg 0 8),
          LocalSet 4,
          LocalGet 4,
          I32Const 48,
          I32LtU,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 4,
          I32Const 57,
          I32GtU,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 9,
          I64Const 10,
          I64Mul,
          LocalGet 4,
          I32Const 48,
          I32Sub,
          I64ExtendI32U,
          I64Add,
          LocalSet 9,
          LocalGet 9,
          I64Const 1,
          I64Const 31,
          I64Shl,
          I64GtS,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          LocalGet 3,
          If BtVoid,
          I64Const 0,
          LocalGet 9,
          I64Sub,
          LocalSet 9,
          Else,
          LocalGet 9,
          I64Const 2147483647,
          I64GtS,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 2,
          End,
          End,
          End,
          LocalGet 8,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 7,
          LocalGet 7,
          I32Const (ptParseError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 7,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 5,
          LocalGet 5,
          LocalGet 9,
          I32WrapI64,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 5,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 6
        ]
    }

-- | @__parseUInt8@: @String -> Either ParseError UInt8@. Decimal digits, range-checked\n--   against @0..255@; @Left ParseError@ otherwise.
parseUInt8Spec :: PreludeTags -> WasmFunc
parseUInt8Spec tags =
  WasmFunc
    { wfName = "__parseUInt8",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ I32Const 0,
          LocalSet 8,
          I32Const 0,
          LocalSet 3,
          LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          Block BtVoid,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 1,
          End,
          I32Const 0,
          LocalSet 2,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 2,
          LocalGet 1,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Load8U (MemArg 0 8),
          LocalSet 4,
          LocalGet 4,
          I32Const 48,
          I32LtU,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 4,
          I32Const 57,
          I32GtU,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 3,
          I32Const 10,
          I32Mul,
          LocalGet 4,
          I32Const 48,
          I32Sub,
          I32Add,
          LocalSet 3,
          LocalGet 3,
          I32Const 255,
          I32GtU,
          If BtVoid,
          I32Const 1,
          LocalSet 8,
          Br 3,
          End,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          End,
          LocalGet 8,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 7,
          LocalGet 7,
          I32Const (ptParseError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 7,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 5,
          LocalGet 5,
          LocalGet 3,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 6,
          LocalGet 5,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 6
        ]
    }

-- | @__parseUInt32@: @String -> Either ParseError UInt32@. Decimal digits accumulated\n--   in an @i64@ (last slot), range-checked against @UINT32_MAX@.
parseUInt32Spec :: PreludeTags -> WasmFunc
parseUInt32Spec tags =
  WasmFunc
    { wfName = "__parseUInt32",
      wfParams = [I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I64],
      wfBody =
        [ I32Const 0,
          LocalSet 7,
          I64Const 0,
          LocalSet 8,
          LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 1,
          Block BtVoid,
          LocalGet 1,
          I32Eqz,
          If BtVoid,
          I32Const 1,
          LocalSet 7,
          Br 1,
          End,
          I32Const 0,
          LocalSet 2,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 2,
          LocalGet 1,
          I32GeU,
          BrIf 1,
          LocalGet 0,
          LocalGet 2,
          I32Add,
          I32Load8U (MemArg 0 8),
          LocalSet 3,
          LocalGet 3,
          I32Const 48,
          I32LtU,
          If BtVoid,
          I32Const 1,
          LocalSet 7,
          Br 3,
          End,
          LocalGet 3,
          I32Const 57,
          I32GtU,
          If BtVoid,
          I32Const 1,
          LocalSet 7,
          Br 3,
          End,
          LocalGet 8,
          I64Const 10,
          I64Mul,
          LocalGet 3,
          I32Const 48,
          I32Sub,
          I64ExtendI32U,
          I64Add,
          LocalSet 8,
          LocalGet 8,
          I64Const 4294967295,
          I64GtU,
          If BtVoid,
          I32Const 1,
          LocalSet 7,
          Br 3,
          End,
          LocalGet 2,
          I32Const 1,
          I32Add,
          LocalSet 2,
          Br 0,
          End,
          End,
          End,
          LocalGet 7,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 6,
          LocalGet 6,
          I32Const (ptParseError tags),
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptLeft tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 6,
          I32Store (MemArg 2 4),
          Else,
          I32Const 4,
          Call "__alloc",
          LocalSet 4,
          LocalGet 4,
          LocalGet 8,
          I32WrapI64,
          I32Store (MemArg 2 0),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 5,
          LocalGet 5,
          I32Const (ptRight tags),
          I32Store (MemArg 2 0),
          LocalGet 5,
          LocalGet 4,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 5
        ]
    }

-- | @__splitOnFirst(sep, s)@: split @s@ on the first occurrence of @sep@, returning\n--   @Just (Tuple2 before after)@ or @Nothing@. UTF-16 prefix lengths via\n--   @__utf16_of_range@; payloads copied with @__memcpy@.
splitOnFirstSpec :: PreludeTags -> WasmFunc
splitOnFirstSpec tags =
  WasmFunc
    { wfName = "__splitOnFirst",
      wfParams = [I32, I32],
      wfResults = [I32],
      wfLocals = [I32, I32, I32, I32, I32, I32, I32, I32, I32, I32, I32, I32],
      wfBody =
        [ LocalGet 0,
          I32Load (MemArg 2 0),
          LocalSet 2,
          LocalGet 1,
          I32Load (MemArg 2 0),
          LocalSet 3,
          I32Const (-1),
          LocalSet 6,
          I32Const 0,
          LocalSet 4,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 4,
          LocalGet 2,
          I32Add,
          LocalGet 3,
          I32GtU,
          BrIf 1,
          I32Const 0,
          LocalSet 5,
          I32Const 1,
          LocalSet 7,
          Block BtVoid,
          Loop BtVoid,
          LocalGet 5,
          LocalGet 2,
          I32Eq,
          BrIf 1,
          LocalGet 1,
          LocalGet 4,
          I32Add,
          LocalGet 5,
          I32Add,
          I32Load8U (MemArg 0 8),
          LocalGet 0,
          LocalGet 5,
          I32Add,
          I32Load8U (MemArg 0 8),
          I32Ne,
          If BtVoid,
          I32Const 0,
          LocalSet 7,
          Br 2,
          End,
          LocalGet 5,
          I32Const 1,
          I32Add,
          LocalSet 5,
          Br 0,
          End,
          End,
          LocalGet 7,
          If BtVoid,
          LocalGet 4,
          LocalSet 6,
          Br 2,
          End,
          LocalGet 4,
          I32Const 1,
          I32Add,
          LocalSet 4,
          Br 0,
          End,
          End,
          LocalGet 6,
          I32Const (-1),
          I32Eq,
          If BtVoid,
          I32Const 4,
          Call "__alloc",
          LocalSet 11,
          LocalGet 11,
          I32Const (ptNothing tags),
          I32Store (MemArg 2 0),
          Else,
          LocalGet 6,
          I32Const 8,
          I32Add,
          Call "__alloc",
          LocalSet 8,
          LocalGet 8,
          LocalGet 6,
          I32Store (MemArg 2 0),
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 6,
          Call "__utf16_of_range",
          LocalSet 13,
          LocalGet 8,
          LocalGet 13,
          I32Store (MemArg 2 4),
          LocalGet 8,
          I32Const 8,
          I32Add,
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 6,
          Call "__memcpy",
          LocalGet 3,
          LocalGet 6,
          I32Sub,
          LocalGet 2,
          I32Sub,
          LocalSet 12,
          LocalGet 12,
          I32Const 8,
          I32Add,
          Call "__alloc",
          LocalSet 9,
          LocalGet 9,
          LocalGet 12,
          I32Store (MemArg 2 0),
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 6,
          I32Add,
          LocalGet 2,
          I32Add,
          LocalGet 12,
          Call "__utf16_of_range",
          LocalSet 13,
          LocalGet 9,
          LocalGet 13,
          I32Store (MemArg 2 4),
          LocalGet 9,
          I32Const 8,
          I32Add,
          LocalGet 1,
          I32Const 8,
          I32Add,
          LocalGet 6,
          I32Add,
          LocalGet 2,
          I32Add,
          LocalGet 12,
          Call "__memcpy",
          I32Const 12,
          I32Const 2,
          Call "__alloc_shaped",
          LocalSet 10,
          LocalGet 10,
          I32Const (ptTuple2 tags),
          I32Store (MemArg 2 0),
          LocalGet 10,
          LocalGet 8,
          I32Store (MemArg 2 4),
          LocalGet 10,
          LocalGet 9,
          I32Store (MemArg 2 8),
          I32Const 8,
          I32Const 1,
          Call "__alloc_shaped",
          LocalSet 11,
          LocalGet 11,
          I32Const (ptJust tags),
          I32Store (MemArg 2 0),
          LocalGet 11,
          LocalGet 10,
          I32Store (MemArg 2 4),
          End,
          LocalGet 0,
          Call "__free_recursive",
          LocalGet 1,
          Call "__free_recursive",
          LocalGet 11
        ]
    }
