; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object
.field private static __argv [Ljava/lang/String;

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 4
  .limit locals 1
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 3
  .limit locals 7
L_tco0:
  aload_0
  checkcast [Ljava/lang/Object;
  astore_1
  aload_1
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  iconst_5
  if_icmpne L_tarm1
  aload_1
  iconst_1
  aaload
  astore_3
  aconst_null
  astore 4
  aload_3
  aconst_null
  astore_3
  areturn
L_tarm1:
  aload_1
  iconst_1
  aaload
  astore_3
  aload_1
  iconst_2
  aaload
  astore 4
  aload_3
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 5
  aload 5
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 6
  aload 4
  aconst_null
  astore_0
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_0
  goto L_tco0
.end method


.method static v_firstZero(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 3
  .limit locals 7
  aload_0
  checkcast [Ljava/lang/Object;
  astore_1
  aload_1
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 10
  if_icmpne L_arm3
  aconst_null
  astore_3
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  goto L_join2
L_arm3:
  aload_1
  iconst_1
  aaload
  astore_3
  aload_3
  checkcast [Ljava/lang/Object;
  astore 4
  aload 4
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 5
  iload 5
  bipush 10
  if_icmpne L_arm5
  aconst_null
  astore 6
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  goto L_join4
L_arm5:
  aload 4
  iconst_1
  aaload
  astore 6
  aload 6
L_join4:
L_join2:
  areturn
.end method


.method static v_main()Ljava/lang/Object;
  .limit stack 10
  .limit locals 0
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 10
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__lift_12(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_firstZero(Ljava/lang/Object;)Ljava/lang/Object;
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/toString()Ljava/lang/String;
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  areturn
.end method


.method static v__lift_12(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 4
  .limit locals 4
  aload_0
  checkcast [Ljava/lang/Object;
  astore_1
  aload_1
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 10
  if_icmpne L_arm7
  aconst_null
  astore_3
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 10
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  goto L_join6
L_arm7:
  aload_1
  iconst_1
  aaload
  astore_3
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 11
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
L_join6:
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 5
  .limit locals 1
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  putstatic AwsumMain/__argv [Ljava/lang/String;
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
