; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object
.field private static __argv [Ljava/lang/String;

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 4
  .limit locals 1
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static __predInt32(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 3
  aload_0
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_1
  iload_1
  ldc -2147483648
  if_icmpne L_pred_ok
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_pred_ok:
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iload_1
  iconst_1
  isub
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static __eqInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 2
  aload_0
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  if_icmpne L_eq_i32_ne
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
L_eq_i32_ne:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static __addInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 6
  aload_0
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_2
  iload_3
  iadd
  istore 4
  iload_2
  iload 4
  ixor
  iload_3
  iload 4
  ixor
  iand
  iflt L_addi32_over
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iload 4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
L_addi32_over:
  iload_2
  iflt L_addi32_under
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 17
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 5
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 882564211
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  astore 5
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  areturn
L_addi32_under:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 5
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc -526521719
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  astore 5
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 3
  .limit locals 7
L_tco0:
  aload_0
  checkcast [Ljava/lang/Object;
  astore_1
  aload_1
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  iconst_5
  if_icmpne L_tarm1
  aload_1
  iconst_1
  aaload
  astore_3
  aconst_null
  astore 4
  aload_3
  aconst_null
  astore_3
  areturn
L_tarm1:
  aload_1
  iconst_1
  aaload
  astore_3
  aload_1
  iconst_2
  aaload
  astore 4
  aload_3
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 5
  aload 5
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 6
  aload 4
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_0
  goto L_tco0
.end method


.method static v_buildLeft(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 8
  .limit locals 7
L_tco2:
  aload_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__eqInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore_2
  aload_2
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_3
  iconst_1
  if_icmpne L_tarm3
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  areturn
L_tarm3:
  aload_0
  invokestatic AwsumMain/__predInt32(Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 4
  aload 4
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 5
  iload 5
  iconst_3
  if_icmpne L_tarm4
  aload 4
  iconst_1
  aaload
  astore 6
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  aconst_null
  astore 6
  areturn
L_tarm4:
  aload 4
  iconst_1
  aaload
  astore 6
  aload 6
  iconst_4
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 23
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_3
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 22
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aconst_null
  astore 6
  astore_1
  astore_0
  goto L_tco2
.end method


.method static v_addOr0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 3
  .limit locals 5
  aload_0
  aload_1
  invokestatic AwsumMain/__addInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore_2
  aload_2
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_3
  iconst_3
  if_icmpne L_arm6
  aload_2
  iconst_1
  aaload
  astore 4
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  goto L_join5
L_arm6:
  aload_2
  iconst_1
  aaload
  astore 4
  aload 4
L_join5:
  areturn
.end method


.method static v_sumTree(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 7
  .limit locals 2
  aload_0
  aload_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 24
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps_sumTree(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v_main()Ljava/lang/Object;
  .limit stack 10
  .limit locals 3
  ldc 100000
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 22
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v_buildLeft(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore_0
  aload_0
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_1
  iload_1
  iconst_3
  if_icmpne L_arm8
  aload_0
  iconst_1
  aaload
  astore_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "UNDERFLOW"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join7
L_arm8:
  aload_0
  iconst_1
  aaload
  astore_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/v_sumTree(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/toString()Ljava/lang/String;
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
L_join7:
  areturn
.end method


.method static v__scc__apply_sumTree__cps_sumTree(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 7
  .limit locals 11
L_tco9:
  aload_0
  checkcast [Ljava/lang/Object;
  astore_1
  aload_1
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 26
  if_icmpne L_tarm10
  aload_1
  iconst_1
  aaload
  astore_3
  aload_1
  iconst_2
  aaload
  astore 4
  aconst_null
  astore 5
  aload_3
  checkcast [Ljava/lang/Object;
  astore 6
  aload 6
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 7
  iload 7
  bipush 24
  if_icmpne L_tarm11
  aconst_null
  astore 8
  aconst_null
  astore 9
  aload 4
  aconst_null
  astore 4
  aconst_null
  astore_3
  areturn
L_tarm11:
  aload 6
  iconst_1
  aaload
  astore 8
  aload 6
  iconst_2
  aaload
  astore 9
  iconst_4
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 27
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 9
  aastore
  dup
  iconst_2
  aload 4
  aastore
  dup
  iconst_3
  aload 8
  aastore
  aconst_null
  astore 9
  aconst_null
  astore 8
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_0
  goto L_tco9
L_tarm10:
  aload_1
  iconst_1
  aaload
  astore_3
  aload_1
  iconst_2
  aaload
  astore 4
  aload_1
  iconst_3
  aaload
  astore 5
  aload_3
  checkcast [Ljava/lang/Object;
  astore 6
  aload 6
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 7
  iload 7
  bipush 22
  if_icmpne L_tarm12
  aconst_null
  astore 8
  aconst_null
  astore 9
  aconst_null
  astore 10
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  dup
  iconst_2
  aload 4
  aastore
  aconst_null
  astore 5
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_0
  goto L_tco9
L_tarm12:
  aload 6
  iconst_1
  aaload
  astore 8
  aload 6
  iconst_2
  aaload
  astore 9
  aload 6
  iconst_3
  aaload
  astore 10
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 27
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 8
  aastore
  dup
  iconst_2
  aload 4
  aload 9
  invokestatic AwsumMain/v_addOr0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aastore
  dup
  iconst_3
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 25
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  dup
  iconst_2
  aload 10
  aastore
  aastore
  aconst_null
  astore 10
  aconst_null
  astore 9
  aconst_null
  astore 8
  aconst_null
  astore 5
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_0
  goto L_tco9
.end method


.method static v__cps_sumTree(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 3
  iconst_4
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 27
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  dup
  iconst_2
  aload_1
  aastore
  dup
  iconst_3
  aload_2
  aastore
  invokestatic AwsumMain/v__scc__apply_sumTree__cps_sumTree(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 5
  .limit locals 1
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  putstatic AwsumMain/__argv [Ljava/lang/String;
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
