; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object
.field private static __argv [Ljava/lang/String;

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 3
  aload_0
  checkcast java/lang/String
  invokevirtual java/lang/String/length()I
  i2l
  aload_1
  checkcast java/lang/String
  invokevirtual java/lang/String/length()I
  i2l
  ladd
  lconst_1
  bipush 27
  lshl
  lcmp
  ifgt L_concat_too_long
  aload_0
  checkcast java/lang/String
  aload_1
  checkcast java/lang/String
  invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_concat_too_long:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 19
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 4
  .limit locals 1
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 3
  .limit locals 5
L_tco0:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  iconst_5
  if_icmpne L_tarm1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  areturn
L_tarm1:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  aconst_null
  astore_1
  astore_0
  goto L_tco0
.end method


.method static v__cps_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 5
L_tco2:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 13
  if_icmpne L_tarm3
  aconst_null
  astore_3
  aconst_null
  astore 4
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "Nil"
  aastore
  invokestatic AwsumMain/v__apply_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tarm3:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore_3
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 4
  aload 4
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco2
.end method


.method static v__apply_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 10
L_tco4:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 15
  if_icmpne L_tarm5
  aconst_null
  astore_3
  aload_1
  areturn
L_tarm5:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore_3
  aload_1
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 5
  iload 5
  iconst_3
  if_icmpne L_tarm6
  aconst_null
  astore 6
  aload_3
  aload_1
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco4
L_tarm6:
  aload_1
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore 6
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  ldc ","
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 7
  aload 7
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 8
  iload 8
  iconst_3
  if_icmpne L_tarm7
  aload 7
  iconst_1
  aaload
  astore 9
  aload_3
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 9
  aastore
  aconst_null
  astore 9
  aconst_null
  astore 6
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco4
L_tarm7:
  aload 7
  iconst_1
  aaload
  astore 9
  aload_3
  aload 9
  aload 6
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore 9
  aconst_null
  astore 6
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco4
.end method


.method static v_main()Ljava/lang/Object;
  .limit stack 13
  .limit locals 22
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 13
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_0
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 4
  iload 4
  bipush 13
  if_icmpne L_arm11
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "Nothing"
  aastore
  goto L_join10
L_arm11:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 7
  aload 7
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 8
  iload 8
  iconst_3
  if_icmpne L_arm13
  aload 7
  iconst_1
  aaload
  astore 9
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 9
  aastore
  goto L_join12
L_arm13:
  aload 7
  iconst_1
  aaload
  astore 9
  ldc "Just "
  aload 9
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_join12:
L_join10:
  checkcast [Ljava/lang/Object;
  astore 4
  aload 4
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 5
  iload 5
  iconst_3
  if_icmpne L_jarm14
  aconst_null
  astore 6
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "STRING_TOO_LONG"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_jafter9
L_jarm14:
  aload 4
  iconst_1
  aaload
  astore 6
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "a"
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 13
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore_1
  aload_1
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 7
  iload 7
  bipush 13
  if_icmpne L_arm16
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "Nothing"
  aastore
  goto L_join15
L_arm16:
  aload_1
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 10
  aload 10
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 11
  iload 11
  iconst_3
  if_icmpne L_arm18
  aload 10
  iconst_1
  aaload
  astore 12
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 12
  aastore
  goto L_join17
L_arm18:
  aload 10
  iconst_1
  aaload
  astore 12
  ldc "Just "
  aload 12
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_join17:
L_join15:
  checkcast [Ljava/lang/Object;
  astore 7
  aload 7
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 8
  iload 8
  iconst_3
  if_icmpne L_arm20
  aload 7
  iconst_1
  aaload
  astore 9
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 9
  aastore
  goto L_join19
L_arm20:
  aload 7
  iconst_1
  aaload
  astore 9
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "a"
  aastore
  dup
  iconst_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "b"
  aastore
  dup
  iconst_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "c"
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 13
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  aastore
  astore_2
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 10
  iload 10
  bipush 13
  if_icmpne L_arm22
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "Nothing"
  aastore
  goto L_join21
L_arm22:
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps_showList(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 13
  aload 13
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 14
  iload 14
  iconst_3
  if_icmpne L_arm24
  aload 13
  iconst_1
  aaload
  astore 15
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 15
  aastore
  goto L_join23
L_arm24:
  aload 13
  iconst_1
  aaload
  astore 15
  ldc "Just "
  aload 15
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_join23:
L_join21:
  checkcast [Ljava/lang/Object;
  astore 10
  aload 10
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 11
  iload 11
  iconst_3
  if_icmpne L_arm26
  aload 10
  iconst_1
  aaload
  astore 12
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 12
  aastore
  goto L_join25
L_arm26:
  aload 10
  iconst_1
  aaload
  astore 12
  aload 6
  ldc "|"
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 13
  aload 13
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 14
  iload 14
  iconst_3
  if_icmpne L_arm28
  aload 13
  iconst_1
  aaload
  astore 15
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 15
  aastore
  goto L_join27
L_arm28:
  aload 13
  iconst_1
  aaload
  astore 15
  aload 15
  aload 9
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 16
  aload 16
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 17
  iload 17
  iconst_3
  if_icmpne L_arm30
  aload 16
  iconst_1
  aaload
  astore 18
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 18
  aastore
  goto L_join29
L_arm30:
  aload 16
  iconst_1
  aaload
  astore 18
  aload 18
  ldc "|"
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  checkcast [Ljava/lang/Object;
  astore 19
  aload 19
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 20
  iload 20
  iconst_3
  if_icmpne L_arm32
  aload 19
  iconst_1
  aaload
  astore 21
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 21
  aastore
  goto L_join31
L_arm32:
  aload 19
  iconst_1
  aaload
  astore 21
  aload 21
  aload 12
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_join31:
L_join29:
L_join27:
L_join25:
L_join19:
  astore_3
  goto L_jbody8
L_jbody8:
  aload_3
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 4
  iload 4
  iconst_3
  if_icmpne L_arm34
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "STRING_TOO_LONG"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join33
L_arm34:
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
L_join33:
L_jafter9:
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 5
  .limit locals 1
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  putstatic AwsumMain/__argv [Ljava/lang/String;
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
