; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_1
  dup
  iconst_2
  aaload
  astore_2
  pop
  aload_1
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_2
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  invokestatic AwsumMain/__getArgs()Ljava/lang/Object;
  invokestatic AwsumMain/v__apply1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  astore_0
  goto L_tco_loop
.end method


.method static v_say(Ljava/lang/Object;)Ljava/lang/Object;
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  areturn
.end method


.method static v_handleInputErr(Ljava/lang/Object;)Ljava/lang/Object;
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "INPUT_ERROR"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  areturn
.end method


.method static v_main()Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  invokestatic AwsumMain/v__df_andThenIO_2(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_1
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__io_getargs_cont(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_join:
  areturn
.end method


.method static v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  aload_2
  invokestatic AwsumMain/v_handleInputErr(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_1
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__df_andThenIO_2(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  aload_2
  invokestatic AwsumMain/v_say(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__apply__df_andThenIO_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_1
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore 4
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore 4
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_2:
  pop
  aload_1
  aload_3
  invokestatic AwsumMain/v__io_getargs_cont(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore 4
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__apply__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    1: L_tco_arm_1
    2: L_tco_arm_2
    3: L_tco_arm_3
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_1
  areturn
L_tco_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_andThenIO_2(Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_3:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__apply1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  dup
  iconst_2
  aload_1
  aastore
  invokestatic AwsumMain/v__scc__apply1__df__lam_3_3__df__lam_6_1__lift_2(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method static __entryArgEither(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 8
  aload_0
  checkcast java/lang/String
  astore_1
  aload_1
  invokevirtual java/lang/String/length()I
  istore_2
  iload_2
  ldc 134217728
  if_icmpgt L_entry_too_long
  iconst_0
  istore_3
  iconst_0
  istore 4
L_entry_scan:
  iload_3
  iload_2
  if_icmpge L_entry_scan_done
  aload_1
  iload_3
  invokevirtual java/lang/String/charAt(I)C
  ldc 64512
  iand
  istore 5
  iload 4
  ifne L_entry_check_low
  iload 5
  ldc 56320
  if_icmpeq L_entry_unpaired
  iload 5
  ldc 55296
  if_icmpne L_entry_inc
  iconst_1
  istore 4
  goto L_entry_inc
L_entry_check_low:
  iload 5
  ldc 56320
  if_icmpne L_entry_unpaired
  iconst_0
  istore 4
  goto L_entry_inc
L_entry_inc:
  iinc 3 1
  goto L_entry_scan
L_entry_scan_done:
  iload 4
  ifne L_entry_unpaired
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  areturn
L_entry_too_long:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 6
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 589989748
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  astore 7
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  areturn
L_entry_unpaired:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 6
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 502975519
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  astore 7
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  areturn
.end method

.method static __getArgs()Ljava/lang/Object;
  .limit stack 2
  .limit locals 1
  ldc "awsum.argv0"
  invokestatic java/lang/System/getProperty(Ljava/lang/String;)Ljava/lang/String;
  invokestatic AwsumMain/__entryArgEither(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  arraylength
  iconst_1
  if_icmpge has_arg
  ldc ""
  goto call_main
has_arg:
  aload_0
  iconst_0
  aaload
call_main:
  checkcast java/lang/String
  ldc "awsum.argv0"
  swap
  invokestatic java/lang/System/setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  pop
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
