; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object
.field private static __argv [Ljava/lang/String;

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 4
  .limit locals 1
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 2
  .limit locals 3
L_tco0:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  iconst_5
  if_icmpne L_tarm1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  areturn
L_tarm1:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  aconst_null
  astore_1
  astore_0
  goto L_tco0
.end method


.method static v_main()Ljava/lang/Object;
  .limit stack 7
  .limit locals 15
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc -1583721377
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 24
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore_0
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 10
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  checkcast [Ljava/lang/Object;
  astore 11
  aload 11
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 12
  iload 12
  ldc 1615808600
  if_icmpne L_arm3
  aload 10
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 14
  iload 14
  bipush 24
  if_icmpne L_arm5
  ldc "sA"
  goto L_join4
L_arm5:
  ldc "sB"
L_join4:
  goto L_join2
L_arm3:
  aload 10
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 14
  iload 14
  bipush 24
  if_icmpne L_arm7
  ldc "iA"
  goto L_join6
L_arm7:
  ldc "iB"
L_join6:
L_join2:
  astore 7
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore 8
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  dup
  iconst_2
  aload 8
  aastore
  astore 5
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 31
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 6
  aload 5
  aload 6
  invokestatic AwsumMain/v_$cps$$df$andThenIO$8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  astore_3
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 29
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 4
  aload_3
  aload 4
  invokestatic AwsumMain/v_$cps$$df$andThenIO$4(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  astore_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 27
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  aload_1
  aload_2
  invokestatic AwsumMain/v_$cps$$df$andThenIO$0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v_$cps$$df$andThenIO$0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 7
  .limit locals 16
L_tco8:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_3
  iconst_5
  if_icmpne L_tarm9
  aconst_null
  astore 4
  aconst_null
  astore 5
  aload_1
  astore 6
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 1615808600
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "x"
  aastore
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 25
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore_2
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 11
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  checkcast [Ljava/lang/Object;
  astore 12
  aload 12
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 13
  iload 13
  ldc 1615808600
  if_icmpne L_arm11
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm13
  ldc "sA"
  goto L_join12
L_arm13:
  ldc "sB"
L_join12:
  goto L_join10
L_arm11:
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm15
  ldc "iA"
  goto L_join14
L_arm15:
  ldc "iB"
L_join14:
L_join10:
  astore 8
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore 9
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 8
  aastore
  dup
  iconst_2
  aload 9
  aastore
  astore 7
  aload 6
  aload 7
  invokestatic AwsumMain/v_$apply$$df$andThenIO$0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tarm9:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore 4
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 5
  aload 5
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 28
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload 4
  aastore
  aconst_null
  astore 5
  aconst_null
  astore 4
  astore_1
  astore_0
  goto L_tco8
.end method


.method static v_$apply$$df$andThenIO$0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 5
L_tco16:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 27
  if_icmpne L_tarm17
  aconst_null
  astore_3
  aload_1
  areturn
L_tarm17:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore_3
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aload_1
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco16
.end method


.method static v_$cps$$df$andThenIO$4(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 7
  .limit locals 16
L_tco18:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_3
  iconst_5
  if_icmpne L_tarm19
  aconst_null
  astore 4
  aconst_null
  astore 5
  aload_1
  astore 6
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 1615808600
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "x"
  aastore
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 24
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore_2
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 11
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  checkcast [Ljava/lang/Object;
  astore 12
  aload 12
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 13
  iload 13
  ldc 1615808600
  if_icmpne L_arm21
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm23
  ldc "sA"
  goto L_join22
L_arm23:
  ldc "sB"
L_join22:
  goto L_join20
L_arm21:
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm25
  ldc "iA"
  goto L_join24
L_arm25:
  ldc "iB"
L_join24:
L_join20:
  astore 8
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore 9
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 8
  aastore
  dup
  iconst_2
  aload 9
  aastore
  astore 7
  aload 6
  aload 7
  invokestatic AwsumMain/v_$apply$$df$andThenIO$4(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tarm19:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore 4
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 5
  aload 5
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 30
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload 4
  aastore
  aconst_null
  astore 5
  aconst_null
  astore 4
  astore_1
  astore_0
  goto L_tco18
.end method


.method static v_$apply$$df$andThenIO$4(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 5
L_tco26:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 29
  if_icmpne L_tarm27
  aconst_null
  astore_3
  aload_1
  areturn
L_tarm27:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore_3
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aload_1
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco26
.end method


.method static v_$cps$$df$andThenIO$8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 7
  .limit locals 16
L_tco28:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_3
  iload_3
  iconst_5
  if_icmpne L_tarm29
  aconst_null
  astore 4
  aconst_null
  astore 5
  aload_1
  astore 6
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc -1583721377
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  dup
  iconst_2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 25
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore_2
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 11
  aload_2
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  checkcast [Ljava/lang/Object;
  astore 12
  aload 12
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 13
  iload 13
  ldc 1615808600
  if_icmpne L_arm31
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm33
  ldc "sA"
  goto L_join32
L_arm33:
  ldc "sB"
L_join32:
  goto L_join30
L_arm31:
  aload 11
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore 15
  iload 15
  bipush 24
  if_icmpne L_arm35
  ldc "iA"
  goto L_join34
L_arm35:
  ldc "iB"
L_join34:
L_join30:
  astore 8
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  astore 9
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 8
  aastore
  dup
  iconst_2
  aload 9
  aastore
  astore 7
  aload 6
  aload 7
  invokestatic AwsumMain/v_$apply$$df$andThenIO$8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
L_tarm29:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore 4
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  astore 5
  aload 5
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 32
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload 4
  aastore
  aconst_null
  astore 5
  aconst_null
  astore 4
  astore_1
  astore_0
  goto L_tco28
.end method


.method static v_$apply$$df$andThenIO$8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 5
L_tco36:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  istore_2
  iload_2
  bipush 31
  if_icmpne L_tarm37
  aconst_null
  astore_3
  aload_1
  areturn
L_tarm37:
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aaload
  astore_3
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_1
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aaload
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  iconst_2
  aload_1
  aastore
  aload_0
  checkcast [Ljava/lang/Object;
  aconst_null
  astore 4
  aconst_null
  astore_3
  astore_1
  astore_0
  goto L_tco36
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 5
  .limit locals 1
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  putstatic AwsumMain/__argv [Ljava/lang/String;
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
