; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 51.0
.class public AwsumMain
.super java/lang/Object

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  checkcast java/lang/String
  aload_1
  checkcast java/lang/String
  invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
  areturn
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  aconst_null
  areturn
.end method

.method static __mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 3
  aload_0
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  imul
  istore_2
  iload_2
  sipush 255
  if_icmple L_mulu8_ok
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_mulu8_ok:
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iload_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static v_showOverflowError(Ljava/lang/Object;)Ljava/lang/Object;
  ldc "OverflowError"
  areturn
.end method


.method static v_render(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  ldc "overflow: "
  aload_1
  invokestatic AwsumMain/v_showOverflowError(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  ldc "ok: "
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/toString()Ljava/lang/String;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  areturn
.end method


.method static v_main(Ljava/lang/Object;)Ljava/lang/Object;
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  bipush 17
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  sipush 255
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  sipush 255
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  sipush 200
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  sipush 200
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  invokestatic AwsumMain/__mulUInt8(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  aload_0
  arraylength
  iconst_1
  if_icmpge has_arg
  ldc ""
  goto call_main
has_arg:
  aload_0
  iconst_0
  aaload
call_main:
  invokestatic AwsumMain/v_main(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
