; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 3
  aload_0
  checkcast java/lang/String
  invokevirtual java/lang/String/length()I
  i2l
  aload_1
  checkcast java/lang/String
  invokevirtual java/lang/String/length()I
  i2l
  ladd
  ldc2_w 134217728
  lcmp
  ifgt L_concat_too_long
  aload_0
  checkcast java/lang/String
  aload_1
  checkcast java/lang/String
  invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_concat_too_long:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static __splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 5
  .limit locals 4
  aload_1
  checkcast java/lang/String
  aload_0
  checkcast java/lang/String
  invokevirtual java/lang/String/indexOf(Ljava/lang/String;)I
  istore_2
  iload_2
  iconst_m1
  if_icmpne L_split_found
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
L_split_found:
  aload_1
  checkcast java/lang/String
  iconst_0
  iload_2
  invokevirtual java/lang/String/substring(II)Ljava/lang/String;
  astore_3
  aload_1
  checkcast java/lang/String
  iload_2
  aload_0
  checkcast java/lang/String
  invokevirtual java/lang/String/length()I
  iadd
  invokevirtual java/lang/String/substring(I)Ljava/lang/String;
  astore_2
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_2
  aastore
  astore_3
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  areturn
.end method

.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    2: L_tco_arm_2
    default: L_tco_arm_0
L_tco_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  areturn
L_tco_arm_2:
  dup
  iconst_1
  aaload
  astore_1
  dup
  iconst_2
  aaload
  astore_2
  pop
  aload_1
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_2
  astore_0
  goto L_tco_loop
.end method


.method static v_render(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "Nothing"
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  aload_3
  invokestatic AwsumMain/v_renderTuple(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  goto L_join
L_join:
  areturn
.end method


.method static v_renderTuple(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  ldc "Just("
  aload_0
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  ldc "|"
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_3
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_3
  pop
  aload_3
  aload_1
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 4
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload 4
  ldc ")"
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  areturn
.end method


.method static v_main(Ljava/lang/Object;)Ljava/lang/Object;
  ldc ","
  ldc "a,b,c"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  ldc "::"
  ldc "user::42::admin"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_2
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_2
  pop
  ldc "x"
  ldc "abc"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_3
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_3
  pop
  ldc ""
  ldc "abc"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 4
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 4
  pop
  ldc ":"
  ldc ":foo"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 5
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 5
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 5
  pop
  ldc ":"
  ldc "foo:"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 6
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 6
  pop
  ldc "abc"
  ldc "abc"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 7
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 7
  pop
  ldc "abcde"
  ldc "ab"
  invokestatic AwsumMain/__splitOnFirst(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_render(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 8
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 8
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 8
  pop
  aload_1
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 9
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 9
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 9
  pop
  aload 9
  aload_2
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 10
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 10
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 10
  pop
  aload 10
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 11
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 11
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 11
  pop
  aload 11
  aload_3
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 12
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 12
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 12
  pop
  aload 12
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 13
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 13
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 13
  pop
  aload 13
  aload 4
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 14
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 14
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 14
  pop
  aload 14
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 15
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 15
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 15
  pop
  aload 15
  aload 5
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 16
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 16
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 16
  pop
  aload 16
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 17
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 17
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 17
  pop
  aload 17
  aload 6
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 18
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 18
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 18
  pop
  aload 18
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 19
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 19
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 19
  pop
  aload 19
  aload 7
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 20
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 20
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 20
  pop
  aload 20
  ldc ", "
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore 21
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 21
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore 21
  pop
  aload 21
  aload 8
  invokestatic AwsumMain/__concat(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  goto L_join
L_join:
  invokestatic AwsumMain/v__let_2(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__let_2(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_arm_0
    1: L_arm_1
    default: L_arm_0
L_arm_0:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "STRING_TOO_LONG"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_arm_1:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_join:
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  arraylength
  iconst_1
  if_icmpge has_arg
  ldc ""
  goto call_main
has_arg:
  aload_0
  iconst_0
  aaload
call_main:
  astore_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  invokestatic AwsumMain/v_main(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
