; Awsum JVM codegen — Jasmin-like syntax, not compatible with Jasmin.
; This is a textual representation of the bytecode generated by assembleJVM.
.bytecode 55.0
.class public AwsumMain
.super java/lang/Object

.method <init>()V
  aload_0
  invokespecial java/lang/Object/<init>()V
  return
.end method

.method static __print(Ljava/lang/Object;)Ljava/lang/Object;
  getstatic java/lang/System/out Ljava/io/PrintStream;
  aload_0
  invokevirtual java/io/PrintStream/print(Ljava/lang/Object;)V
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  areturn
.end method

.method static __addInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 3
  aload_0
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  i2l
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  i2l
  ladd
  dup2
  ldc2_w 2147483647
  lcmp
  ifgt L_addi32_over
  dup2
  ldc2_w -2147483648
  lcmp
  iflt L_addi32_under
  l2i
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_addi32_over:
  pop2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
L_addi32_under:
  pop2
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  areturn
.end method

.method static v_pureEither(Ljava/lang/Object;)Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  areturn
.end method


.method static v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    5: L_tco_arm_5
    7: L_tco_arm_7
    8: L_tco_arm_8
    9: L_tco_arm_9
    default: L_tco_arm_5
L_tco_arm_5:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  aconst_null
  astore_1
  areturn
L_tco_arm_7:
  dup
  iconst_1
  aaload
  astore_1
  dup
  iconst_2
  aaload
  astore_2
  pop
  aload_1
  invokestatic AwsumMain/__print(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    0: L_tco_arm_0
    default: L_tco_arm_0
L_tco_arm_0:
  pop
  aload_2
  aconst_null
  astore_0
  aconst_null
  astore_2
  aconst_null
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_8:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  invokestatic AwsumMain/__getArgs()Ljava/lang/Object;
  invokestatic AwsumMain/v__apply1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_0
  aconst_null
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_9:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  invokestatic AwsumMain/__stdinReadAll()Ljava/lang/Object;
  invokestatic AwsumMain/v__apply1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_0
  aconst_null
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v_opTuple(Ljava/lang/Object;)Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_4
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 13
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_2
  iconst_2
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_3
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  areturn
.end method


.method static v_processInput(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  invokestatic AwsumMain/v_opTuple(Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    3: L_arm_3
    4: L_arm_4
    default: L_arm_3
L_arm_3:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_arm_4:
  dup
  iconst_1
  aaload
  astore_1
  pop
  aload_1
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    13: L_arm_13
    default: L_arm_13
L_arm_13:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  dup
  iconst_3
  aaload
  astore 4
  pop
  aload_2
  aload_3
  invokestatic AwsumMain/__addInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    3: L_arm_3
    4: L_arm_4
    default: L_arm_3
L_arm_3:
  dup
  iconst_1
  aaload
  astore 5
  pop
  aload 4
  goto L_join
L_arm_4:
  dup
  iconst_1
  aaload
  astore 5
  pop
  aload 5
  aload 4
  invokestatic AwsumMain/__addInt32(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    3: L_arm_3
    4: L_arm_4
    default: L_arm_3
L_arm_3:
  dup
  iconst_1
  aaload
  astore 6
  pop
  aload 4
  goto L_join
L_arm_4:
  dup
  iconst_1
  aaload
  astore 6
  pop
  aload 6
  goto L_join
L_join:
  goto L_join
L_join:
  invokestatic AwsumMain/v_pureEither(Ljava/lang/Object;)Ljava/lang/Object;
  goto L_join
L_join:
  goto L_join
L_join:
  invokestatic AwsumMain/v__let_12(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v_handleInputErr(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    502975519: L_arm_502975519
    589989748: L_arm_589989748
    default: L_arm_502975519
L_arm_502975519:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "UNPAIRED_UTF16_SURROGATE"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_arm_589989748:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "STRING_TOO_LONG"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_join:
  areturn
.end method


.method static v_main()Ljava/lang/Object;
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 8
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 18
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  invokestatic AwsumMain/v__df_andThenIO_3(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 28
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    5: L_tco_arm_5
    6: L_tco_arm_6
    7: L_tco_arm_7
    8: L_tco_arm_8
    9: L_tco_arm_9
    default: L_tco_arm_5
L_tco_arm_5:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_6:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 6
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_7:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 29
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_8:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 8
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 19
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_9:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 9
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 20
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
.end method


.method static v__apply__lift_1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    28: L_tco_arm_28
    29: L_tco_arm_29
    default: L_tco_arm_28
L_tco_arm_28:
  pop
  aload_1
  areturn
L_tco_arm_29:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__let_12(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    3: L_arm_3
    4: L_arm_4
    default: L_arm_3
L_arm_3:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  ldc "PARSE_ERROR"
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_arm_4:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/toString()Ljava/lang/String;
  aastore
  dup
  iconst_2
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_0
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  aastore
  aastore
  goto L_join
L_join:
  areturn
.end method


.method static v__io_getargs_cont(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    3: L_arm_3
    4: L_arm_4
    default: L_arm_3
L_arm_3:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 6
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_arm_4:
  dup
  iconst_1
  aaload
  astore_1
  pop
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  goto L_join
L_join:
  areturn
.end method


.method static v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 30
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    5: L_tco_arm_5
    6: L_tco_arm_6
    7: L_tco_arm_7
    8: L_tco_arm_8
    9: L_tco_arm_9
    default: L_tco_arm_5
L_tco_arm_5:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_5
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_6:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  aload_2
  invokestatic AwsumMain/v_handleInputErr(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_7:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 31
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_8:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 8
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 14
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_9:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 9
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 15
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
.end method


.method static v__apply__df_handleErrorIO_0(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    30: L_tco_arm_30
    31: L_tco_arm_31
    default: L_tco_arm_30
L_tco_arm_30:
  pop
  aload_1
  areturn
L_tco_arm_31:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__df_andThenIO_3(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 32
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    5: L_tco_arm_5
    6: L_tco_arm_6
    7: L_tco_arm_7
    8: L_tco_arm_8
    9: L_tco_arm_9
    default: L_tco_arm_5
L_tco_arm_5:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  aload_2
  invokestatic AwsumMain/v_processInput(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_6:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 6
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  invokestatic AwsumMain/v__apply__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_7:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_3
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 33
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  dup
  iconst_2
  aload_2
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_8:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 8
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
L_tco_arm_9:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 9
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 17
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  aastore
  invokestatic AwsumMain/v__apply__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_2
  areturn
.end method


.method static v__apply__df_andThenIO_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    32: L_tco_arm_32
    33: L_tco_arm_33
    default: L_tco_arm_32
L_tco_arm_32:
  pop
  aload_1
  areturn
L_tco_arm_33:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 7
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_3
  aastore
  dup
  iconst_2
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;)Ljava/lang/Object;
  aload_0
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 34
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  invokestatic AwsumMain/v__cps__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method


.method static v__cps__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    21: L_tco_arm_21
    22: L_tco_arm_22
    23: L_tco_arm_23
    24: L_tco_arm_24
    25: L_tco_arm_25
    26: L_tco_arm_26
    27: L_tco_arm_27
    default: L_tco_arm_21
L_tco_arm_21:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_2
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    14: L_tco_arm_14
    15: L_tco_arm_15
    16: L_tco_arm_16
    17: L_tco_arm_17
    18: L_tco_arm_18
    19: L_tco_arm_19
    20: L_tco_arm_20
    default: L_tco_arm_14
L_tco_arm_14:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 22
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_15:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 23
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_16:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 24
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_17:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 25
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_18:
  pop
  aload_1
  aload_3
  invokestatic AwsumMain/v__io_getargs_cont(Ljava/lang/Object;)Ljava/lang/Object;
  invokestatic AwsumMain/v__apply__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_3
  aconst_null
  astore_2
  areturn
L_tco_arm_19:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 26
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_20:
  dup
  iconst_1
  aaload
  astore 4
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 27
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 4
  aastore
  dup
  iconst_2
  aload_3
  aastore
  aload_1
  aconst_null
  astore_1
  aconst_null
  astore 4
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_22:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 35
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_23:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 36
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_24:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 37
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_25:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 38
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_26:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 39
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_27:
  dup
  iconst_1
  aaload
  astore_2
  dup
  iconst_2
  aaload
  astore_3
  pop
  aload_0
  checkcast [Ljava/lang/Object;
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_2
  aastore
  dup
  iconst_2
  aload_3
  aastore
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 40
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_1
  aastore
  aconst_null
  astore_1
  aconst_null
  astore_3
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__apply__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
L_tco_loop:
  aload_0
  dup
  iconst_0
  aaload
  checkcast java/lang/Integer
  invokevirtual java/lang/Integer/intValue()I
  lookupswitch
    34: L_tco_arm_34
    35: L_tco_arm_35
    36: L_tco_arm_36
    37: L_tco_arm_37
    38: L_tco_arm_38
    39: L_tco_arm_39
    40: L_tco_arm_40
    default: L_tco_arm_34
L_tco_arm_34:
  pop
  aload_1
  areturn
L_tco_arm_35:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_36:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_handleErrorIO_0(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_37:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_andThenIO_3(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_38:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__df_andThenIO_3(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_39:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
L_tco_arm_40:
  dup
  iconst_1
  aaload
  astore_2
  pop
  aload_2
  aload_1
  invokestatic AwsumMain/v__lift_1(Ljava/lang/Object;)Ljava/lang/Object;
  aconst_null
  astore_1
  aconst_null
  astore_0
  aconst_null
  astore_2
  astore_1
  astore_0
  goto L_tco_loop
.end method


.method static v__apply1(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  iconst_3
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 21
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  dup
  iconst_2
  aload_1
  aastore
  invokestatic AwsumMain/v__scc__apply1__df__lam_10_1__df__lam_11_2__df__lam_4_4__df__lam_5_5__lift_2__lift_3(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method static __entryArgEither(Ljava/lang/Object;)Ljava/lang/Object;
  .limit stack 6
  .limit locals 8
  aload_0
  checkcast java/lang/String
  astore_1
  aload_1
  invokevirtual java/lang/String/length()I
  istore_2
  iload_2
  ldc 134217728
  if_icmpgt L_entry_too_long
  iconst_0
  istore_3
  iconst_0
  istore 4
L_entry_scan:
  iload_3
  iload_2
  if_icmpge L_entry_scan_done
  aload_1
  iload_3
  invokevirtual java/lang/String/charAt(I)C
  ldc 64512
  iand
  istore 5
  iload 4
  ifne L_entry_check_low
  iload 5
  ldc 56320
  if_icmpeq L_entry_unpaired
  iload 5
  ldc 55296
  if_icmpne L_entry_inc
  iconst_1
  istore 4
  goto L_entry_inc
L_entry_check_low:
  iload 5
  ldc 56320
  if_icmpne L_entry_unpaired
  iconst_0
  istore 4
  goto L_entry_inc
L_entry_inc:
  iinc 3 1
  goto L_entry_scan
L_entry_scan_done:
  iload 4
  ifne L_entry_unpaired
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_4
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload_0
  aastore
  areturn
L_entry_too_long:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 16
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 6
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 589989748
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  astore 7
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  areturn
L_entry_unpaired:
  iconst_1
  anewarray java/lang/Object
  dup
  iconst_0
  bipush 17
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  astore 6
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  ldc 502975519
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 6
  aastore
  astore 7
  iconst_2
  anewarray java/lang/Object
  dup
  iconst_0
  iconst_3
  invokestatic java/lang/Integer/valueOf(I)Ljava/lang/Integer;
  aastore
  dup
  iconst_1
  aload 7
  aastore
  areturn
.end method

.method static __getArgs()Ljava/lang/Object;
  .limit stack 2
  .limit locals 1
  ldc "awsum.argv0"
  invokestatic java/lang/System/getProperty(Ljava/lang/String;)Ljava/lang/String;
  invokestatic AwsumMain/__entryArgEither(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method static __stdinReadAll()Ljava/lang/Object;
  .limit stack 4
  .limit locals 3
  new java/io/ByteArrayOutputStream
  dup
  invokespecial java/io/ByteArrayOutputStream/<init>()V
  astore_0
  sipush 8192
  newarray byte
  astore_1
L_stdin_loop:
  getstatic java/lang/System/in Ljava/io/InputStream;
  aload_1
  iconst_0
  sipush 8192
  invokevirtual java/io/InputStream/read([BII)I
  istore_2
  iload_2
  ifle L_stdin_done
  aload_0
  aload_1
  iconst_0
  iload_2
  invokevirtual java/io/ByteArrayOutputStream/write([BII)V
  goto L_stdin_loop
L_stdin_done:
  aload_0
  invokevirtual java/io/ByteArrayOutputStream/toByteArray()[B
  astore_1
  new java/lang/String
  dup
  aload_1
  getstatic java/nio/charset/StandardCharsets/UTF_8 Ljava/nio/charset/Charset;
  invokespecial java/lang/String/<init>([BLjava/nio/charset/Charset;)V
  invokestatic AwsumMain/__entryArgEither(Ljava/lang/Object;)Ljava/lang/Object;
  areturn
.end method

.method public static main([Ljava/lang/String;)V
  new java/io/PrintStream
  dup
  new java/io/FileOutputStream
  dup
  getstatic java/io/FileDescriptor/out Ljava/io/FileDescriptor;
  invokespecial java/io/FileOutputStream/<init>(Ljava/io/FileDescriptor;)V
  iconst_1
  ldc "UTF-8"
  invokespecial java/io/PrintStream/<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
  invokestatic java/lang/System/setOut(Ljava/io/PrintStream;)V
  aload_0
  arraylength
  iconst_1
  if_icmpge has_arg
  ldc ""
  goto call_main
has_arg:
  aload_0
  iconst_0
  aaload
call_main:
  checkcast java/lang/String
  ldc "awsum.argv0"
  swap
  invokestatic java/lang/System/setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  pop
  invokestatic AwsumMain/v_main()Ljava/lang/Object;
  invokestatic AwsumMain/v_runIO(Ljava/lang/Object;)Ljava/lang/Object;
  pop
  return
.end method
