{-# OPTIONS_GHC -Wno-orphans #-}

module Awsum.ArbitraryInstances () where

import Awsum.Syntax
import Data.Char
  ( GeneralCategory (LineSeparator, ParagraphSeparator, Surrogate),
    generalCategory,
    isAsciiLower,
    isAsciiUpper,
    isControl,
    toLower,
    toUpper,
  )
import Data.Text qualified as T
import Relude
import Test.QuickCheck

identTailChar :: Gen Char
identTailChar =
  frequency
    [ (6, elements (['a' .. 'z'] <> ['A' .. 'Z'])),
      (3, elements ['0' .. '9']),
      (1, elements ['_', '\''])
    ]

reserved :: [Text]
reserved =
  [ "import",
    "type",
    "case",
    "of",
    "do",
    "class",
    "instance",
    "where",
    "if",
    "then",
    "else",
    "match",
    "with",
    "let",
    "in",
    "rec"
  ]

mkSafe :: (Char -> Char) -> Gen Text
mkSafe firstCase = sized $ \n -> do
  k <- chooseInt (0, max 0 (min 6 n)) -- tail length
  c0 <- suchThat arbitrary isAlpha -- first char must be a letter
  cs <- vectorOf k identTailChar
  let raw = toText (firstCase c0 : cs)
  if T.toLower raw `elem` reserved then mkSafe firstCase else pure raw
  where
    isAlpha c = isAsciiLower c || isAsciiUpper c

genLIdent :: Gen Name
genLIdent = mkSafe toLower

genUIdent :: Gen Name
genUIdent = mkSafe toUpper

-- | Shrink an identifier to its prefixes, excluding reserved words — the
--   generator ('mkSafe') never produces a reserved word, so the shrinker
--   must not either (e.g. shrinking @ind@ toward @in@ would yield a
--   keyword used as a name, which no valid program contains).
shrinkIdent :: Name -> [Name]
shrinkIdent t =
  let s = toString t
   in filter (\p -> T.toLower p `notElem` reserved) [toText (take k s) | k <- [1 .. length s - 1]]

genNonEmpty :: Gen a -> Gen (NonEmpty a)
genNonEmpty g = (:|) <$> g <*> listOf g

shrinkNonEmpty :: (a -> [a]) -> NonEmpty a -> [NonEmpty a]
shrinkNonEmpty sh (x :| xs) =
  -- 1) shrink head
  [x' :| xs | x' <- sh x]
    <>
    -- 2) shrink tail (keeping at least one element)
    [ y :| ys
    | (y : ys) <- shrinkList sh (x : xs),
      not (null (y : ys))
    ]

-- ───────────────────────── Arbitrary instances ─────────────────────────

instance Arbitrary ImportDecl where
  arbitrary = ImportDecl <$> genLeadingComments <*> genNonEmpty genUIdent <*> genComment
  shrink (ImportDecl _ ne _) = ImportDecl [] <$> shrinkNonEmpty shrinkIdent ne <*> pure Nothing

-- | Prefer producing useful types for tests:
--   • 'TyVar' appears often (so polymorphic sigs like 'a -> b -> a' show up),
--   • 'TyCon' is biased toward known ones ("String", "IO"), but can be any UIdent,
--   • 'TyArrow' recurses with smaller sizes.
instance Arbitrary Type' where
  arbitrary = sized go
    where
      go 0 =
        frequency
          [ (3, TyVar noSpan <$> genTyVarName),
            (3, TyCon noSpan <$> genKnownTyCon),
            (2, TyCon noSpan <$> genUIdent)
          ]
      go n =
        frequency
          [ (4, TyVar noSpan <$> genTyVarName),
            (3, TyCon noSpan <$> genKnownTyCon),
            (2, TyCon noSpan <$> genUIdent),
            (3, TyApp noSpan <$> go (n `div` 2) <*> go (n `div` 2)),
            (6, TyArrow noSpan <$> go (n `div` 2) <*> go (n `div` 2)),
            (2, TyOr noSpan <$> go (n `div` 2) <*> go (n `div` 2))
          ]

      -- small, readable type variable names; still valid 'lident'
      genTyVarName :: Gen Name
      genTyVarName =
        frequency
          [ (6, elements (map one ['a' .. 'f'])), -- common short vars
            (4, genLIdent)
          ]

      genKnownTyCon :: Gen Name
      genKnownTyCon = elements ["String", "IO"]

  shrink = \case
    TyVar _ v -> TyVar noSpan <$> shrinkIdent v
    TyCon _ n -> TyCon noSpan <$> shrinkIdent n
    -- 'TyEmpty' isn't generated by 'Arbitrary' (the parser only
    -- produces 'TyCon' references; the typechecker resolves to
    -- 'TyEmpty' later). Round-trip property tests therefore won't
    -- encounter it organically. The branch is here only so 'shrink'
    -- is exhaustive over 'Type''.
    TyEmpty _ n -> TyEmpty noSpan <$> shrinkIdent n
    TyApp _ f x ->
      [f, x]
        <> [TyApp noSpan f' x | f' <- shrink f]
        <> [TyApp noSpan f x' | x' <- shrink x]
    TyArrow _ a b ->
      [a, b]
        <> [TyArrow noSpan a' b | a' <- shrink a]
        <> [TyArrow noSpan a b' | b' <- shrink b]
    TyOr _ a b ->
      [a, b]
        <> [TyOr noSpan a' b | a' <- shrink a]
        <> [TyOr noSpan a b' | b' <- shrink b]

instance Arbitrary QName where
  arbitrary = do
    -- 0..2 module segments (UIdent), then name (lident)
    k <- frequency [(3, pure 0), (2, pure 1), (1, pure 2)]
    mods <- replicateM k genUIdent
    QName mods <$> genLIdent
  shrink (QName ms n) =
    -- shrink module prefix and the base name
    [QName (take i ms) n | i <- [0 .. length ms - 1]]
      <> [QName ms n' | n' <- shrinkIdent n]

-- | Text for string literals and comments. Spans the width classes that
--   matter for layout — narrow, wide East-Asian (two display columns), and
--   supplementary (two UTF-16 code units) — so the round-trip and idempotency
--   properties exercise the display-width alignment in 'Awsum.Render' (shared
--   with 'Awsum.Lsp'), not only ASCII. Excludes what breaks the round-trip for
--   reasons unrelated to width: control characters and line or paragraph
--   separators (a literal newline would split a line comment), the
--   block-comment delimiters @{@ and @}@, and quote or backslash.
genStr :: Gen Text
genStr = do
  k <- chooseInt (0, 8)
  toText <$> vectorOf k genStrChar

genStrChar :: Gen Char
genStrChar = suchThat gen ok
  where
    gen =
      frequency
        [ (5, chr <$> chooseInt (0x20, 0x7E)), -- printable ASCII (narrow)
          (2, chr <$> chooseInt (0x3000, 0x9FFF)), -- wide BMP (CJK & co.)
          (1, chr <$> chooseInt (0x00A1, 0x024F)), -- narrow non-ASCII BMP
          (1, chr <$> chooseInt (0x1D400, 0x1D7FF)), -- narrow supplementary
          (1, chr <$> chooseInt (0x20000, 0x2A6DF)) -- wide supplementary
        ]
    ok c =
      not (isControl c)
        && generalCategory c
        `notElem` [LineSeparator, ParagraphSeparator, Surrogate]
        && c
        `notElem` ['{', '}', '"', '\\']

-- | Single-line comment text. Empty texts are valid in the AST but
--   the renderer emits them as a bare @--@ that the parser
--   canonicalises back to 'Nothing'; the property's normaliser
--   ('normalizeTrailing') matches that on both sides, so empty
--   texts round-trip too.
genCommentText :: Gen Text
genCommentText = genStr

genComment :: Gen (Maybe Text)
genComment = frequency [(3, pure Nothing), (1, Just <$> genCommentText)]

-- | Generator for the text inside a 'BlockComment' that survives the
--   render→parse round-trip. The renderer wraps the trimmed body as
--   @{- body -}@ (single spaces around it), and the parser captures
--   everything between the delimiters verbatim — so the AST text
--   must be @" body "@ (one space, no-whitespace-on-edges body, one
--   space). Force that shape here.
genBlockCommentText :: Gen Text
genBlockCommentText = do
  inner <- genCommentText `suchThat` (not . T.null . T.strip)
  pure (" " <> T.strip inner <> " ")

-- | A single comment node — line or block.
genCommentNode :: Gen Comment
genCommentNode =
  oneof
    [ LineComment <$> genCommentText,
      BlockComment <$> genBlockCommentText
    ]

-- | Leading-comments list for positions that accept any number of
--   comments before the syntactic element they attach to. Mostly empty
--   so the round-trip property keeps exercising the comment-free
--   shapes too.
genLeadingComments :: Gen [Comment]
genLeadingComments =
  frequency
    [ (4, pure []),
      (2, vectorOf 1 genCommentNode),
      (1, vectorOf 2 genCommentNode)
    ]

-- | Doc-comment text that survives the @render → parse@ round-trip
--   through the attached @{- text -}@ form. Three constraints fall
--   out from how 'Awsum.Parser.attachDocs' processes the captured
--   text, all met by construction here:
--
--   1. /Not all-whitespace./ 'attachDocs' applies @T.strip@; an
--      all-whitespace text would normalise to @""@ which
--      'normalizeTrailing' then rewrites to 'Nothing', breaking
--      equality with the generated @Just t@.
--
--   2. /Already 'T.strip'-ed./ Leading/trailing whitespace is dropped
--      by the parser's strip, so it must be absent on the generated
--      side too.
--
--   3. /No @{-@ or @-}@ substrings./ The balanced parser would
--      consume them as nested-block delimiters; an unbalanced one
--      closes the outer block prematurely. 'genStr' excludes @{@ and
--      @}@ entirely, so the substring constraint is automatic — we
--      only need to enforce 1 and 2.
--
--   Mostly single-line content; a small fraction joins two lines with
--   a newline so the multi-line markdown shape (also produced by
--   stacked @--@ source) is also exercised.
genDocCommentText :: Gen Text
genDocCommentText = do
  parts <-
    frequency
      [ (3, vectorOf 1 genStr),
        (1, vectorOf 2 genStr)
      ]
  let t = T.strip (T.intercalate "\n" parts)
  if T.null t then genDocCommentText else pure t

-- | Optional doc-comment. Leans heavily towards 'Nothing' so generated
--   programs stay small; when a doc is produced, its text comes from
--   'genDocCommentText' so the @render → parse@ round-trip is exact.
genDocComment :: Gen (Maybe Text)
genDocComment =
  frequency
    [ (5, pure Nothing),
      (1, Just <$> genDocCommentText)
    ]

genInt :: Gen Integer
genInt =
  frequency
    [ (3, choose (-2147483648, 2147483647)), -- Int32 range
      (2, choose (0, 255)) -- UInt8 range
    ]

-- | Patterns are size-bounded so 'PCon' fields don't explode.
--   Generated forms cover all four surface shapes; type ascriptions
--   carry a (small) 'Type'' and the inner pattern is rendered via
--   'renderPattern' (which already wraps 'PAscribe' in parens).
instance Arbitrary Pattern where
  arbitrary = sized go
    where
      go 0 =
        oneof
          [ PVar noSpan <$> genLIdent,
            PWild noSpan <$ pass,
            PCon noSpan <$> genUIdent <*> pure []
          ]
      go n =
        frequency
          [ (3, PVar noSpan <$> genLIdent),
            (2, pure (PWild noSpan)),
            (3, PCon noSpan <$> genUIdent <*> pure []),
            ( 2,
              do
                k <- chooseInt (1, min 2 n)
                PCon noSpan <$> genUIdent <*> vectorOf k (go (n `div` (k + 1)))
            ),
            (1, PAscribe noSpan <$> go (n `div` 2) <*> resize (n `div` 2) arbitrary)
          ]
  shrink = \case
    PVar _ n -> PVar noSpan <$> shrinkIdent n
    PWild _ -> []
    PCon _ n ps ->
      PCon noSpan n []
        : [PCon noSpan n' ps | n' <- shrinkIdent n]
          <> [PCon noSpan n ps' | ps' <- shrinkList shrink ps]
    PAscribe _ p t -> p : [PAscribe noSpan p' t | p' <- shrink p] <> [PAscribe noSpan p t' | t' <- shrink t]

-- | A function or lambda parameter: mostly a plain name, with an
--   occasional destructuring / type-ascribed 'ParamPat'. Shared by the
--   'Decl' ('FunDef') and 'Expr' (lambda) generators so both exercise the
--   same parameter surface — including the type-ascription form @(n : T)@,
--   which both @f (n : T) = …@ and @\\(n : T) -> …@ accept.
--
--   The parser canonicalises @(x)@ back to a bare 'Param' (see
--   'paramBinderG' in the parser); the normaliser ('normalizeParam')
--   matches that on the AST side and runs on lambda params too, so any
--   'ParamPat' shape — @PVar@, @PWild@, @PCon@, @PAscribe@ — round-trips
--   through @parse∘render@ once both sides are normalised.
genParam :: Gen Param
genParam =
  frequency
    [ (8, Param noSpan <$> genLIdent),
      (1, ParamPat noSpan <$> genParamPat)
    ]

genParamPat :: Gen Pattern
genParamPat =
  oneof
    [ PVar noSpan <$> genLIdent,
      pure (PWild noSpan),
      PCon noSpan <$> genUIdent <*> pure [],
      do
        k <- chooseInt (1, 2)
        PCon noSpan <$> genUIdent <*> vectorOf k (resize 1 arbitrary),
      PAscribe noSpan <$> resize 1 arbitrary <*> resize 2 arbitrary
    ]

instance Arbitrary ConDef where
  arbitrary = sized $ \n -> do
    name <- genUIdent
    k <- chooseInt (0, min 2 (max 0 n))
    -- The full 'Type'' arbitrary (including TyApp / TyArrow / TyOr).
    -- The renderer parenthesises non-atomic fields ('renderConDef'
    -- uses precedence 4), so the parse∘render round-trip survives
    -- arbitrary nested types in field position.
    fs <- vectorOf k (resize (n `div` 2) arbitrary)
    pure (ConDef noSpan name fs)
  shrink (ConDef _ n fs) =
    [ConDef noSpan n' fs | n' <- shrinkIdent n]
      <> [ConDef noSpan n (take i fs) | i <- [0 .. length fs - 1]]

instance Arbitrary CaseAlt where
  arbitrary = sized $ \n -> do
    pat <- resize (n `div` 2) arbitrary
    body <- resize (n `div` 2) arbitrary
    -- Trailing '--' on a CaseAlt only round-trips when the body's
    -- render ends on the same line as the arm (so the parser's
    -- 'pTrailingLineCommentMaybe' lands on the comment instead of
    -- finding empty space past a newline). 'isBlockBody' captures
    -- exactly that distinction; the type-level split into
    -- 'CaseAltLeaf' / 'CaseAltBlock' upgrades the rule from
    -- "generator avoids it" to "AST disallows the bad pairing", and
    -- 'mkCaseAlt' picks the right variant for us.
    mc <- if isBlockBody body then pure Nothing else genComment
    pure (mkCaseAlt [] pat body mc)
  shrink alt =
    let p = caseAltPattern alt
        e = caseAltBody alt
     in [mkCaseAlt [] p' e Nothing | p' <- shrink p]
          <> [mkCaseAlt [] p e' Nothing | e' <- shrink e]

-- | A 'do'-block statement. The renderer goes through
--   'renderPatternAtom' for the LHS, which parenthesises constructor
--   applications and leaves PAscribe self-parenthesised — so any
--   pattern shape works on a single line with the '='. The optional
--   type ascription mirrors the standalone 'let n : T = e' form.
-- | Generate the optional ascription for a let-binding: 'Nothing' most of
--   the time, otherwise a type paired with a layout. An own-line signature
--   is only valid for a simple binder (the parser's 'requirePVar'), so a
--   destructuring pattern only ever gets an inline ascription — matching
--   the parser keeps 'render ∘ parse' a fixed point.
genLetSigAnnot :: Int -> Pattern -> Gen (Maybe (Type', LetSigLayout))
genLetSigAnnot sz pat =
  frequency
    [ (3, pure Nothing),
      (1, Just <$> ((,) <$> resize sz arbitrary <*> elements layouts))
    ]
  where
    layouts = case pat of
      PVar _ _ -> [InlineSig, OwnLineSig]
      _ -> [InlineSig]

instance Arbitrary DoStmt where
  arbitrary = sized $ \n ->
    frequency
      [ (3, DoBind noSpan <$> resize (n `div` 2) arbitrary <*> resize (n `div` 2) arbitrary),
        ( 2,
          do
            pat <- resize (n `div` 2) arbitrary
            mAnnot <- genLetSigAnnot (n `div` 2) pat
            e <- resize (n `div` 2) arbitrary
            pure (DoLet noSpan pat mAnnot e)
        ),
        (3, DoExpr noSpan <$> resize (n `div` 2) arbitrary)
      ]
  shrink = \case
    DoBind _ p e -> [DoBind noSpan p' e | p' <- shrink p] <> [DoBind noSpan p e' | e' <- shrink e]
    DoLet _ p t e -> [DoLet noSpan p t e' | e' <- shrink e]
    DoExpr _ e -> DoExpr noSpan <$> shrink e

-- | Surface expressions.
--
--   'ECase' / 'EDo' as nested subexpressions are generated. The
--   AST-level invariant on 'CaseAlt' (Leaf vs Block, see 'Awsum.Syntax')
--   guarantees a trailing '--' on an arm whose body is block-form is
--   not constructible — that was the only round-trip hazard here.
instance Arbitrary Expr where
  arbitrary = sized go
    where
      go 0 =
        oneof
          [ EVar noSpan <$> arbitrary,
            EParens noSpan . EVar noSpan <$> arbitrary, -- parentheses around atom for round-trip tests
            ELit noSpan . LString <$> genStr,
            ELit noSpan . LInt <$> genInt,
            ECon noSpan <$> genUIdent,
            EBuiltIn noSpan <$> genLIdent
          ]
      go n =
        frequency
          [ (4, EVar noSpan <$> arbitrary),
            (2, EParens noSpan <$> go (n - 1)),
            (2, ELit noSpan . LString <$> genStr),
            (2, ELit noSpan . LInt <$> genInt),
            (2, ECon noSpan <$> genUIdent),
            (1, EBuiltIn noSpan <$> genLIdent),
            (5, EApp noSpan <$> go (n `div` 2) <*> go (n `div` 2)),
            (5, EInfix noSpan OpConcat <$> go (n `div` 2) <*> go (n `div` 2)),
            (3, EInfix noSpan OpPipe <$> go (n `div` 2) <*> go (n `div` 2)),
            (2, genLam (n `div` 2)),
            (2, genLet (n `div` 2)),
            (2, EAscribe noSpan <$> go (n `div` 2) <*> resize (n `div` 2) arbitrary),
            -- Block forms in nested position. Lower weight + steeper
            -- size division (n `div` 3) — they expand into multi-line
            -- shapes whose parser layout is layout-sensitive; flooding
            -- the generator with deeply nested blocks blows up the
            -- average tree size without proportional coverage gain.
            (1, ECase noSpan <$> go (n `div` 3) <*> resize (n `div` 3) (genNonEmpty arbitrary) <*> pure []),
            (1, EDo noSpan <$> resize (n `div` 3) (genDoBlockExpr (n `div` 3)))
          ]
      genLam n = do
        k <- chooseInt (1, 2)
        ps <- vectorOf k genParam
        ELam noSpan ps <$> go n
      genLet n = do
        name <- genLIdent
        ann <- genLetSigAnnot (n `div` 2) (PVar noSpan name)
        rhs <- go n
        body <- go n
        pure (ELet noSpan (PVar noSpan name) ann rhs body)
  shrink = \case
    ELit _sp (LString t) -> [ELit noSpan (LString t') | t' <- shrinkIdent t]
    ELit _sp (LInt n) -> [ELit noSpan (LInt n') | n' <- shrink n]
    EVar _sp q -> EVar noSpan <$> shrink q
    EParens _sp e -> e : [EParens noSpan e' | e' <- shrink e]
    ECon _sp n -> ECon noSpan <$> shrinkIdent n
    EApp _sp f x -> [f, x] <> [EApp noSpan f' x | f' <- shrink f] <> [EApp noSpan f x' | x' <- shrink x]
    EInfix _sp OpConcat l r ->
      [l, r]
        <> [EInfix noSpan OpConcat l' r | l' <- shrink l]
        <> [EInfix noSpan OpConcat l r' | r' <- shrink r]
    EInfix _sp OpPipe l r ->
      [l, r]
        <> [EInfix noSpan OpPipe l' r | l' <- shrink l]
        <> [EInfix noSpan OpPipe l r' | r' <- shrink r]
    ECase _sp scrut alts cs ->
      [scrut]
        <> map caseAltBody (toList alts)
        <> [ECase noSpan s' alts cs | s' <- shrink scrut]
    EBuiltIn _sp n -> EBuiltIn noSpan <$> shrinkIdent n
    ELam _sp ps body -> body : [ELam noSpan ps body' | body' <- shrink body]
    EDo _sp stmts -> stmts >>= doStmtExprs
      where
        doStmtExprs = \case
          DoBind _ _ e -> [e]
          DoLet _ _ _ e -> [e]
          DoExpr _ e -> [e]
    ELet _sp _ _ e body -> [e, body] <> [ELet noSpan (PVar noSpan "x") Nothing e' body | e' <- shrink e] <> [ELet noSpan (PVar noSpan "x") Nothing e body' | body' <- shrink body]
    EAscribe _sp e ty -> e : [EAscribe noSpan e' ty | e' <- shrink e] <> [EAscribe noSpan e ty' | ty' <- shrink ty]

-- | Body of an 'EDo' block: zero or more leading bind/let/expr
--   statements followed by a final 'DoExpr'. Shared between
--   'Arbitrary Expr' (nested @do@) and 'Arbitrary Decl' (function-body
--   @do@) so both paths obey the same shape constraint.
genDoBlockExpr :: Int -> Gen [DoStmt]
genDoBlockExpr n = do
  k <- chooseInt (0, min 3 (max 0 n))
  leading <- vectorOf k (resize (n `div` (k + 1)) arbitrary)
  finalE <- DoExpr noSpan <$> resize (n `div` (k + 1)) arbitrary
  pure (leading <> [finalE])

-- | Top-level declarations.
instance Arbitrary Decl where
  arbitrary =
    frequency
      [ (4, Sig noSpan <$> genLIdent <*> arbitrary <*> genComment <*> genDocComment),
        (4, genFunDef),
        (1, genTypeDecl),
        -- Top-level comment as a standalone declaration. When sandwiched
        -- between a 'Sig' and a 'FunDef' of the same name, it breaks the
        -- 'groupDeclBlocks' pairing — both ends still round-trip, just
        -- as two separate blocks with the comment between, which is
        -- exactly what the parser produces.
        (1, CommentDecl noSpan <$> genCommentNode)
      ]
    where
      genFunDef = sized $ \n -> do
        name <- genLIdent
        k <- chooseInt (0, min 3 (max 0 n))
        ps <- vectorOf k genParam
        body <- genFunBody (max 0 (n - k))
        tc <- genComment
        FunDef noSpan name ps body tc <$> genDocComment
      -- Function bodies may additionally be 'ECase' or 'EDo' at the
      -- top level — these are layout-sensitive and only round-trip
      -- when the keyword sits at the head of the right-hand side,
      -- not nested inside an application or infix operator. So
      -- they're added here, not inside the generic 'Arbitrary Expr'.
      genFunBody n =
        frequency
          [ (6, resize n arbitrary),
            (1, ECase noSpan <$> resize (n `div` 2) arbitrary <*> resize (n `div` 2) (genNonEmpty arbitrary) <*> pure []),
            (1, EDo noSpan <$> resize (n `div` 2) (genDoBlockExpr n))
          ]
      genTypeDecl = sized $ \n -> do
        name <- genUIdent
        kTv <- chooseInt (0, min 2 (max 0 n))
        -- Type parameters can't be 'ParamPat' (the parser's
        -- 'paramBinderNoLine' is name-only): keep them simple.
        tvars <- vectorOf kTv (Param noSpan <$> genLIdent)
        kCon <- chooseInt (0, min 3 (max 0 n))
        cons <- vectorOf kCon (resize (n `div` 2) arbitrary)
        comment <- genComment
        -- Generated type declarations are 'NotEmpty' so the existing
        -- params/constructors generators stay valid; the parser would
        -- reject 'Empty' kind paired with non-empty params or
        -- constructors. A dedicated generator for the 'empty type X'
        -- form lives in the round-trip tests where the prelude shape
        -- matters.
        TypeDecl noSpan name tvars cons comment NotEmpty <$> genDocComment
  shrink = \case
    Sig _sp n t mc doc ->
      [Sig noSpan n' t mc doc | n' <- shrinkIdent n]
        <> [Sig noSpan n t' mc doc | t' <- shrink t]
    FunDef _sp n as e mc doc ->
      [FunDef noSpan n' as e mc doc | n' <- shrinkIdent n]
        <> [FunDef noSpan n (take i as) e mc doc | i <- [0 .. length as - 1]]
        <> [FunDef noSpan n as e' mc doc | e' <- shrink e]
    TypeDecl _sp n tvs cs mc ek doc ->
      [TypeDecl noSpan n' tvs cs mc ek doc | n' <- shrinkIdent n]
        <> [TypeDecl noSpan n (take i tvs) cs mc ek doc | i <- [0 .. length tvs - 1]]
        <> [TypeDecl noSpan n tvs cs' mc ek doc | cs' <- shrinkList shrink cs]
    CommentDecl _ _ -> []

instance Arbitrary Program where
  arbitrary = do
    -- 'moduleComment' is a syntactic surface feature (a single
    -- optional block comment at the top of the file separated from
    -- the rest by a blank line). Property tests exercise the AST
    -- shape, not the surface header, so always generate 'Nothing'.
    --
    -- The FIRST import is constrained: its leading-comments list
    -- must be empty (the parser rejects leading comments on the
    -- first import — they would be module-comment material). The
    -- regular 'Arbitrary ImportDecl' generator is free to attach
    -- leading comments, so we strip them on whichever import lands
    -- in head position.
    --
    -- The first DECL is similarly constrained when there are no
    -- imports and no module comment: a leading 'CommentDecl' would
    -- render as a free-standing top-of-file comment, which the
    -- parser interprets as a module comment instead (round-tripping
    -- the AST through render/parse would change 'mc=Nothing' to
    -- 'mc=Just'). We resample the first decl until it is not a
    -- 'CommentDecl' in that configuration.
    ims <- listOf arbitrary
    let imsHead = case ims of
          [] -> []
          ImportDecl _ m mc : rest -> ImportDecl [] m mc : rest
    -- at least one top-level declaration
    d0 <- arbitrary `suchThat` validFirstDecl imsHead
    ds <- listOf arbitrary
    pure Program {moduleComment = Nothing, imports = imsHead, decls = d0 : ds}
  shrink (Program mc ims ds) =
    [ Program mc ims' ds
    | ims' <- shrinkList shrink ims,
      validHead ims',
      all (validFirstDecl ims') (viaNonEmpty head ds)
    ]
      <> [ Program mc ims ds'
         | ds' <- shrinkList shrink ds,
           all (validFirstDecl ims) (viaNonEmpty head ds')
         ]
    where
      validHead = \case
        ImportDecl [] _ _ : _ -> True
        [] -> True
        _ -> False

-- | First-decl constraint mirrored from the parser: when a program has
--   no imports, a leading 'CommentDecl' becomes the module comment on
--   parse and so the original 'Decl' shape cannot round-trip through
--   render/parse. Only relevant when 'imports = []'.
validFirstDecl :: [ImportDecl] -> Decl -> Bool
validFirstDecl [] (CommentDecl _ _) = False
validFirstDecl _ _ = True
